### ISSUE TITLE
[OpenBox] Otter always starts in fullscreen

### ISSUE THREAD

**Issue by ghost** [OtterBrowser/otter-browser#597] opened 2014-12-22 08:21 UTC
and does not remember window size
(Linux, Openbox)

**Comment by resbro** [comment] 2015-01-15 05:41
this happens in win 7 and win 8.1 both x64bit. but if you shape the window and create a session and then close it , when you restore the session the size and sidebar state is saved. this is the only way Ive found so far to make otter-browser window open to preset window size since weekly 50.

**Comment by Emdek** [comment] 2015-01-28 22:43
@resbro, I have some ideas for possible reason, I'll try it later.

**Comment by resbro** [comment] 2015-01-28 23:13
Cool, thanks!

**Comment by resbro** [comment] 2015-02-24 18:43
The sidebar state is being remembered.now, as of some weeks ago (I don't remember when it started working correctly) However the size of the main window still (as of weekly 60) is not.

Win 7 x64
Otterbrowser weekly 60 x32

**Comment by resbro** [comment] 2015-03-03 20:21
Nope! still having to continue from last session to remember window size...

Weekly 61
Win 7 x32

**Comment by resbro** [comment] 2015-03-19 19:07
Still...

Weekly 63

**Comment by Emdek** [comment] 2015-04-01 08:06
Since #31 is now done there is one less blocker for fixing this issue.

**Comment by ThebestwaytodesignJoinGitHub** [comment] 2015-04-01 12:04
A workaround is to start otter with a command line option, eg:
-geometry 800x740

**Comment by resbro** [comment] 2015-04-21 22:56
still...

Weekly 68

**Comment by Emdek** [comment] 2016-06-15 11:28
@resbro, does it still happen with newer Qt versions?

**Comment by resbro** [comment] 2016-06-15 16:11
Yes



Sent from myMail for iOS


Wednesday, June 15, 2016, 4:29 AM -0700 from notifications@github.com  <notifications@github.com>:

**Comment by resbro** [comment] 2016-06-15 17:06
for me, the webkit editions with windows still use 5.5.1 
the webengine versions use 5.7 but both ways it still happens

win 10
otter weekly 128 x 32webkit  win exe.
otter weekly 128 x 32webengine 7z

**Comment by nortexoid** [comment] 2017-03-06 14:23
The bug still persists until MaximizeNewWindows is set to "No". If you ask me, the default breaks consistency on every desktop environment I know of, and so it should be set to "No" by default.

**Comment by Emdek** [comment] 2017-03-06 14:27
@nortexoid, I'm considering dropping that option completely, since it was originally more suitable for MDI mode anyway (maximizing new subwindows)...

**Comment by nortexoid** [comment] 2017-03-06 14:28
@Emdek That's good to hear! Thanks!

**Comment by Emdek** [comment] 2017-03-08 06:52
@nortexoid, I'll try something different first, probably the problem is not that we do it by default but that we do it too early.

**Comment by Emdek** [comment] 2017-03-10 17:46
@nortexoid, OK, I've just checked how it works in OpenBox and I'm puzzled, it seems to work fine, decoration is visible.
Maybe it doesn't fit such WM well but is technically correct, and I'm not sure how to solve it properly then now...

**Comment by nortexoid** [comment] 2017-03-10 18:50
Well the decoration is also visible on KDE, but the window still always maximizes, even when I set specific window overrides not to which you can do with KWin.

**Comment by Emdek** [comment] 2017-03-10 18:52
@nortexoid, which option is that? I could try to reproduce that, if it's kwin5.
But that would sound more like kwin bug then.

**Comment by nortexoid** [comment] 2017-03-10 21:06
There is an option in kcm, but you can also just right click a window decoration, go to More Actions --> Special Window Settings --> Size and Position, and then force the size to a non-maximal size.

**Comment by Emdek** [comment] 2017-03-18 19:02
For now I've dropped that option and started reusing size of existing main window for new ones, but maximize is still fallback.
I need to rethink it and maybe I'll drop that fallback too.

**Comment by nortexoid** [comment] 2017-03-18 21:00
Great, and thanks very much!

**Comment by resbro** [comment] 2017-08-31 18:24
Thanks for taking another go at this today. I'm getting too old, I cant even remember week 51 anymore!

**Comment by Emdek** [comment] 2017-08-31 18:35
@resbro, really? I totally forgot about this ticket...

**Comment by resbro** [comment] 2017-09-06 16:27
At last! Remembers geometry for the first time in almost three years!!!! week 192 is the charm. Thank you!

Win 10
Otter weekly 192 exe x 64

**Comment by Emdek** [comment] 2017-09-06 16:28
@resbro, OK, so can we close it now? :-D

**Comment by resbro** [comment] 2017-09-06 16:29
As far as I'm concerned, YES !!!!

**Comment by Emdek** [comment] 2017-09-06 16:30
@resbro, OK. ;-)

**Comment by resbro** [comment] 2017-09-06 16:30
Thanks!

**Closed by Emdek** 2017-09-06 16:30 UTC
Labels: bug, component: GUI
