### ISSUE TITLE
Tabs In Chrome

### ISSUE THREAD

**Issue by opticyclic** [OtterBrowser/otter-browser#935] opened 2015-09-09 02:39 UTC
Too much space is taken up by the Window Chrome, Otter Menu, Tabs and Toolbar.

The menu bar can be moved to the Otter menu but the tabs can't be moved to the chrome like other browsers and Opera 12.17.

**Comment by Felipefpl** [comment] 2015-09-09 16:20
Version 1.0.0 will gain a GUI rework it seems, look at the todo list. ;)

**Comment by resbro** [comment] 2015-09-09 20:53
Issue # 30 ?

**Comment by Emdek** [comment] 2015-09-14 20:44
Duplicate of #30.

**Closed by Emdek** 2015-09-14 20:44 UTC
Labels: duplicate
