### ISSUE TITLE
Clicking on a tab

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#998] opened 2015-11-21 21:31 UTC
I don't remember seeing an issue regarding this.

Would it be possible to copy Opera's behavior where clicking the active tab on the tabbar minimizes this tab, either showing the "next active" tab, or showing the grey background if there are no other tab.

**Comment by komoku** [comment] 2015-11-22 15:29
Currently you can create a mouse profile in e.g. (otter config dir)/mouse/mymouse.ini with the following:

    [ActiveTabHandle]
    pressLeft,releaseLeft=ActivatePreviouslyUsedTab

and activate it in otter.conf:
    
    MouseProfilesOrder=mymouse, default, custom

Not a "true minimization" but it will switch to the previously used tab, which works for me. There used to be a conflict if you clicked too fast, due to double click closing tabs by default, but now that that has been removed from the default settings, the behavior is good enough IMO.

**Comment by Emdek** [comment] 2015-11-22 15:32
@beastie1, the point of #77 was to easily add such "gestures". ;-)
And #633 will soon make it even easier.
You can also try ``MinimizeTab``, although it might have some issue right now...

**Closed by Emdek** 2015-11-22 15:32 UTC
Labels: invalid

**Comment by beastie1** [comment] 2015-11-22 16:47
Thank you!

**Comment by VSHY** [comment] 2015-11-23 15:47
The action ActivatePreviouslyUsedTab works wrong.
I have 3 tabs. When I click on 3-rd tab it switch to 2-nd tab (it's correctly). When I click on 2-rd tab it switch to 3-nd tab, but should switch to 1-st tab, bacause the 1-st tab is the PreviouslyUsed for 2-nd tab.

**Comment by komoku** [comment] 2015-11-23 15:58
True, I can reproduce this problem in my setup. Maybe it's worth a different ticket.
