### ISSUE TITLE
Visual bug in tab previews

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#1337] opened 2017-04-09 13:23 UTC
There's a small problem with how Otter draws tab previews for non-HTML pages.

Say you have [this link](https://raw.githubusercontent.com/OtterBrowser/otter-browser/master/README.md). Open the link and position the mouse over the tab. You should see this:
![test](https://cloud.githubusercontent.com/assets/6757832/24837606/844cc438-1d40-11e7-8fb4-8fdb747431b3.jpg)

Even if you activate the tab, go back the previous tab and check the preview, it will still be displayed wrong. So Otter doesn't generate a good preview and never updates the stored preview.

Now, close the tab and open the link again. But this time instead of hovering the mouse to get the preview, activate the tab rapidly (faster than **TabBar/PreviewsAnimationDuration**).
If you go back to the previous tab and check the preview, you'll get this:

![test2](https://cloud.githubusercontent.com/assets/6757832/24837605/844c6524-1d40-11e7-8719-a279655ccaca.jpg)

**Comment by Emdek** [comment] 2017-04-10 20:25
@beastie1, it might be tricky to get it working reliably with plain text pages, I'm guessing that * QWebFrame::contentsSize()* might return inconsistent values in this case, at least with legacy QtWebKit.

I really wish that users of BSD systems could finally taste revived QtWebKit. ;-)

**Comment by Emdek** [comment] 2017-09-18 18:34
@beastie1, since FreeBSD finally got revived QtWebKit and this is reproducible only with legacy versions I have no choice but close it as wontfix. ;-)

**Closed by Emdek** 2017-09-18 18:34 UTC
Labels: component: QtWebKitBackend, wontfix
