### ISSUE TITLE
Can't cancel new topic on Discourse-based forums

### ISSUE THREAD

**Issue by jernejs** [OtterBrowser/otter-browser#674] opened 2015-01-27 23:08 UTC
If you start typing a new topic on Discourse-based forums (such at http://what.thedailywtf.com/ or https://community.imgur.com/), then try to cancel (not post), it doesn't work in Otter - the confirmation message appears when you click "cancel", and the editor disappears, but reappears as soon as you refresh the topic list. To actually get rid of the new topic pop-up, I had to go to the site with another browser, and cancel there.

This happens at least with today's Win64 build (weekly 56, WebKit 538.1, Qt 5.4.0)

**Comment by Emdek** [comment] 2015-01-28 22:09
I can report it upstream later, as such issues are QtWebKit bugs. :-/
I'm hoping to have experimental build with QtWebEngine (see #615) ready for testing for next weekly, under Linux it works like a charm.

**Comment by The-Compiler** [comment] 2015-01-28 22:13
I wonder if they are sending a `DELETE` request with a body - if so, it's the same issue as https://github.com/The-Compiler/qutebrowser/issues/134 and https://bugreports.qt.io/browse/QTBUG-42456 and will be fixed in Qt 5.4.1.

Could easily be confirmed using Wireshark but I need some sleep now!

**Comment by The-Compiler** [comment] 2015-01-29 08:01
Nope, it doesn't send a `DELETE` request, so it seems this is a different issue. I tried at http://try.discourse.org/

**Comment by Emdek** [comment] 2015-08-09 21:07
Can't reproduce using try.discourse.org and Qt 5.5, maybe it got fixed in QtWebKit or something got changed on the website itself.

**Closed by Emdek** 2015-08-09 21:07 UTC
Labels: upstream issue
