### ISSUE TITLE
Regression: no more tab close with middle-click

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#1346] opened 2017-04-15 14:37 UTC
Like the title says, middle-clicking a tab doesn't close it anymore.

**Comment by Emdek** [comment] 2017-04-15 14:43
It is no longer set by default, some people had issues with it (cannot find that ticket anymore)...
You need to set it yourself (either manually or in Preferences), it's part of mouse profile configuration.
As a side note, we are going to change their format soon, but there will be day 0 migration available.

**Comment by cofi89** [comment] 2017-04-15 15:36
@Emdek   
I have it set right ( if I understood correctly^ ), but it doesn't work.  [Screenshot.](http://www.zimagez.com/full/1eb2ef5e82a03f92817defaa1cf6b754e8065be0b88349166924c0fb25bf0a9d6ee9081ac8e5c777d939fa3eee00551788891dc9c0198d72.php)

**Comment by Emdek** [comment] 2017-04-15 15:38
@cofi89, current master?
I'll take a look, might be side effect of recent changes in action handling (pretty much rewrite, not complete yet).

**Comment by Emdek** [comment] 2017-04-15 15:42
Indeed, should be easy to fix.

**Comment by cofi89** [comment] 2017-04-15 15:42
Yep, just built...  
I just tested with other actions and none are working, so it looks like that the actual click is the issue/not being registered.  

Also, after closing and reopening Prefs the actions reset themselves to "Close Tab". 
Eg I set the "middle click" to open new tab --> Apply/Ok --> Test ( not working ) --> Reopen Prefs --> Action are set back to "Close tab".

**Comment by Emdek** [comment] 2017-04-15 15:44
@cofi89, well, as noted they are being rewritten right now, so regressions might happen. ;-)

**Comment by cofi89** [comment] 2017-04-15 15:48
:+1:  
Of course, no problem! :smiley:

**Comment by Emdek** [comment] 2017-04-15 15:56
@cofi89, it seems that we have two separate issues here (plus perhaps third one in case of editor), tab identifier wasn't properly extracted and action was redirected directly to tab, but it was still handled by main window, so effectively it wasn't handled at all (in fact the former part is closely related to the latter).

In simpler words, as part of rewrite actions are now triggered directly on as close as possible layer (currently application, main window or tab), but code that handles some of them needs to be moved to proper layer to get called.

**Comment by Emdek** [comment] 2017-04-15 16:16
There might be some other actions that needs moving, I'll try to check all of them once transition will be finished.
Now I'll check what is wrong with that editor.

**Comment by cofi89** [comment] 2017-04-15 16:27
Understood, thanks for the explanation!  
I wish I knew enough of C++/QT to be able to actually help, but unlike Python/GTK, it's taking much more time and effort for me to get to "I can actually do something usefull" level.  
Anyhow, eventually..... :sweat_smile:  

> There might be some other actions that needs moving, I'll try to check all of them once transition will be finished.  

:+1:

**Comment by Emdek** [comment] 2017-04-15 16:29
@cofi89, I can't reproduce that part concerning the editor, but surely it should finally gain some helper for typing-in gesture steps (well, that one is surely the least obvious part of that editor).
Maybe I'll give it a try after moving preferences to *about:preferences*.

Well, testing and reporting issues itself is important way of supporting the project. ;-)

**Closed by Emdek** 2017-04-15 16:29 UTC
Labels: bug, component: GUI
