### ISSUE TITLE
Wrong filename when downloading

### ISSUE THREAD

**Issue by MazheM** [OtterBrowser/otter-browser#849] opened 2015-06-06 22:19 UTC
When you try to download on sites where links to files not direct, filename in save dialog will be script name.
Example: http://www.armaholic.com/page.php?id=23899
Otter 0.9.06, Win 8.1 x64

**Comment by Emdek** [comment] 2015-06-07 18:47
Duplicate of #800 (yeah, ticket name doesn't suggest that ;-)).

**Closed by Emdek** 2015-06-07 18:47 UTC
Labels: duplicate
