### ISSUE TITLE
[QtWebKit] Closing source tab stops file transfer

### ISSUE THREAD

**Issue by msjasinski** [OtterBrowser/otter-browser#858] opened 2015-06-15 03:16 UTC

**Comment by msjasinski** [comment] 2015-06-15 03:17
Downloads might be resumed when reopened and stopped.

**Comment by msjasinski** [comment] 2015-06-15 03:34
Closing another tab also results in halting downloads!

**Comment by NokTham** [comment] 2015-06-15 09:53
Can't reproduce, closed the transfers manager, and the DL just kept on going till it was finished.

Which OS ur using?

Otter 0.9.07 Weekly 75
Windows 7 64-bit

**Comment by msjasinski** [comment] 2015-06-15 13:42
Fedora LXDE x64, will check on Win XP

**Comment by fguzm** [comment] 2015-06-17 14:55
Oh, it's a bug.. Had this today.

**Comment by msjasinski** [comment] 2015-06-25 20:49
Reproduced on Win XP 32bit

**Comment by Emdek** [comment] 2015-07-06 18:15
Can't reproduce (Kubuntu 64 bit), I've started download of some ISO file and after closing tab and reopening it transfer is still progressing.
Are there any details how exactly it could be reproduced (especially how exactly the transfer was initiated)?

**Comment by fguzm** [comment] 2015-07-14 13:24
Got this issue on twitter rigt now. Browse some images, open the interesting in a new background tab with middle click. Later go to these tabs and download the images via the icon on the lower right. When you close the tab before the download has finished, the transfer gets interrupted. No matter if the transfer manager is open or not.

**Comment by fguzm** [comment] 2015-07-14 13:25
flickr

**Comment by Emdek** [comment] 2015-07-14 13:59
@fguzm, in that case it's different issue than suggested in title of this ticket (maybe that was just a coincidence).
I guess that *QNetworkReply* created by QtWebKit gets deleted so download is stopped.
I'll try to reproduce that, this scenario is very likely.

**Comment by Emdek** [comment] 2015-07-15 11:02
It appears that reply silently fails when parent `QNetworkAccessManager` gets deleted.
There is a way to avoid that but it results in starting download twice. :-/

**Comment by The-Compiler** [comment] 2015-07-15 11:56
What I did in qutebrowser is to reparent the `QNetworkAccessManager` to the application (and make sure to `deleteLater` it when the downloads are finished).

**Comment by Emdek** [comment] 2015-07-15 12:06
@The-Compiler, yeah, I've considered that but it's not perfect either...

**Closed** 2015-07-15 18:42 UTC
Labels: bug, component: QtWebKitBackend, upstream issue
