### ISSUE TITLE
Segmentation fault on exit

### ISSUE THREAD

**Issue by midluk** [OtterBrowser/otter-browser#1229] opened 2017-01-02 12:53 UTC
With current master (391309ae0a0efc0b5e57d5f6cdafde8a13071c0c) otter crashes on exit.

> Thread 1 "otter-browser" received signal SIGSEGV, Segmentation fault.
0x00007fffef2f5f73 in QIconPrivate::~QIconPrivate (this=0x118f010, __in_chrg=<optimized out>) at image/qicon_p.h:70
70              delete engine;

> Thread 1 (Thread 0x7fffdaac5e00 (LWP 7393)):
#0  0x00007fffef2f5f73 in QIconPrivate::~QIconPrivate() (this=0x118f010, __in_chrg=<optimized out>) at image/qicon_p.h:70
#1  0x00007fffef2f5f73 in QIcon::~QIcon() (this=<optimized out>, __in_chrg=<optimized out>) at image/qicon.cpp:687
#2  0x0000000000633700 in Otter::ActionsManager::ActionDefinition::~ActionDefinition() (this=0x11c3080, __in_chrg=<optimized out>) at /mnt/daten/Software/otter-browser/src/core/ActionsManager.h:262
#3  0x0000000000636290 in QVector<Otter::ActionsManager::ActionDefinition>::destruct(Otter::ActionsManager::ActionDefinition*, Otter::ActionsManager::ActionDefinition*) (this=0xd4fd90 <Otter::ActionsManager::m_definitions>, from=0x11c30a8, to=0x11c30f8) at /usr/include/qt5/QtCore/qvector.h:351
#4  0x0000000000635d09 in QVector<Otter::ActionsManager::ActionDefinition>::freeData(QTypedArrayData<Otter::ActionsManager::ActionDefinition>*) (this=0xd4fd90 <Otter::ActionsManager::m_definitions>, x=0x11c1470) at /usr/include/qt5/QtCore/qvector.h:527
#5  0x0000000000634700 in QVector<Otter::ActionsManager::ActionDefinition>::~QVector() (this=0xd4fd90 <Otter::ActionsManager::m_definitions>, __in_chrg=<optimized out>) at /usr/include/qt5/QtCore/qvector.h:75
#6  0x00007fffedf6b410 in __run_exit_handlers (status=0, listp=0x7fffee2f15b8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:83
#7  0x00007fffedf6b46a in __GI_exit (status=<optimized out>) at exit.c:105
#8  0x00007fffedf51408 in __libc_start_main (main=0x622c76 <main(int, char**)>, argc=1, argv=0x7fffffffd748, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffd738) at ../csu/libc-start.c:323
#9  0x00000000006225fa in _start ()

**Comment by Emdek** [comment] 2017-01-02 13:04
Are you using desktop theme icons?
If yes then perhaps Qt picks up SVG variant (confirmed to crash on exit, most likely when SVG icon engine plugin is unloaded).

Duplicate of #889, they finally fixed it in 5.8 (at least worked fine with RC)

**Closed by Emdek** 2017-01-02 13:04 UTC
Labels: duplicate
