### ISSUE TITLE
Flash elements are appearing in other tabs

### ISSUE THREAD

**Issue by Zero3K** [OtterBrowser/otter-browser#1105] opened 2016-03-29 22:22 UTC
When tabs containing sites with certain flash elemets are in the background, their elements are drawn on other displayed tabs. It occurs on sites such as Streamate.com and Showup.tv.

**Comment by Emdek** [comment] 2016-03-30 05:39
Duplicate of #150.

**Closed by Emdek** 2016-03-30 05:39 UTC
Labels: duplicate
