### ISSUE TITLE
Multiple tabs closings with pressLeft+shift -> segfault

### ISSUE THREAD

**Issue by hunderteins** [OtterBrowser/otter-browser#1248] opened 2017-01-26 12:38 UTC
Hello,
  try to open otter-browser, open 3 tabs, close the middle one with pressLeft+shift and open an other tab. The tabbar is either disturbed (tabs laying over others) or the new tab is not shown. Doing this multiple times, otter segfaults, even on windows 7 with default config. There is no problem when closing the tabs with pressMiddle or the close-icon.

That problem apeared first time with 07d35b7d18da1d71e9b91a03e8312c717caf9960 (15. November 2016); around that time, when otter got that drag tab feature on pressLeft and hold.

TIA,
hunderteins
![1](https://cloud.githubusercontent.com/assets/1484695/22331611/a2b20b3e-e3cc-11e6-91a1-7de0640bc921.png)

**Comment by Emdek** [comment] 2017-01-30 13:00
@hunderteins, are you building from master yourself?
It might be the same issue that I'm debugging right now, caused by `Window` not being marked as being about to close and `ContentBlockingInformationWidget` (that icon with counter in Status Bar) trying to access it while it is already destructing its children.
If you can produce backtrace using for example *cdb.exe* then it would be appreciated.

**Comment by Emdek** [comment] 2017-02-05 20:45
Closing due to inactivity.

**Closed by Emdek** 2017-02-05 20:45 UTC
Labels: status: needs info
