### ISSUE TITLE
Build 167: relocation error

### ISSUE THREAD

**Issue by mariokamenjak** [OtterBrowser/otter-browser#1312] opened 2017-03-20 09:35 UTC
Hi, when trying to run the latest appimage I get the following error:
./otter-browser: relocation error: /lib/x86_64-linux-gnu/libssl.so.1.0.0: symbol EVP_seed_cbc, version OPENSSL_1.0.0 not defined in file libcrypto.so.1.0.0 with link time reference

Distribution is Debian testing. Is this a debian issue though?

**Comment by Emdek** [comment] 2017-03-20 09:38
It's more like result of Qt issue with defaulting to load OpenSSL at runtime (their license sucks)...

Duplicate of #1233.

**Closed by Emdek** 2017-03-20 09:38 UTC
Labels: duplicate

**Comment by sjukfan** [comment] 2017-03-23 13:43
mariokamenjak:
Do you have spotify installed? Debian testing have libssl1.0.2 and with that one Otter loads but with some error messages. Seems like libqt5network5 wrongly tries to use libssl1.0.0 instead of libssl1.0.2 if it's installed.

**Comment by mariokamenjak** [comment] 2017-03-23 14:12
I think I have multiple libopenssl installed. But I require the old libopenssl because a program for my college requires it. And obviously I need the newer one as well. How do I check which libopensssl's I have?

**Comment by sjukfan** [comment] 2017-03-23 15:05
You can try dpkg-query -l | grep libssl
I had 1.0.0, 1.0.2, and 1.1 installed her but after I removed 1.0.0 Otter started. Had to remove Spotify though.

**Comment by mariokamenjak** [comment] 2017-07-17 11:53
A bit late but I also have 1.0.0, 1.0.2 and 1.1. With 1.0.0 installed Otter does not start. However without 1.0.0 that other important program also refuses to work. I guess I am just gonna have to wait it out until the guys that made that other program release a new version or until something changes.

**Comment by mariokamenjak** [comment] 2017-08-03 14:05
I finally found a fix.
I have to have installed libssl1.0.0(because of that one app), libssl1.0.2(because QT uses it) and libssl1.1(because GTK uses it). 
So I have to go into the /lib/x86_64-linux-gnu directory, and in my case there are these 3 files:
libssl1.0.0.so
libssl1.0.2.so
libssl1.1.so

What we have to do is to move libssl1.0.0.so to a different location. Make a new folder for it somewhere outside of its original location. Now you have to write a wrapper script that will launch the application that uses ssl1.0.0 with the following variable:
LD_LIBRARY_PATH="/path/to/dir/with/ancientlibssl:$LD_LIBRARY_PATH" ./application
For me the offending application was Cisco's packettracer. Luckily it already had a LD_LIBRARY:PATH defined in it's startup script so I just pasted the old libssl into /opt/path/lib.(NOTE: You have to cut it, not copy).

Now both applications started up. Both Otter and packettracer.
However Otter displayed the ssl warning dialogue and some https sites did not work at all. It was because QT was still confusing uncomfourtable with libssl1.1 being installed. I fixed that by doing: apt install libssl1.0-dev
@Emdek

**Comment by Emdek** [comment] 2017-08-06 13:01
@mariokamenjak, world would be better place if there would be no OpenSSL or if their developers would be more responsible (who breaks backwards compatibility in minor release without providing migration patch?). ;-)
Sadly so far there are no alternative code paths in Qt (at least except macOS, where it can use native APIs), although some libraries (LibreSSL, NSS, wolfSSL etc.) provide compatibility layers (hopefully good enough to make Qt happy).

**Comment by mariokamenjak** [comment] 2017-08-06 13:02
Well I just wanted to make you aware of my fix.

**Comment by Emdek** [comment] 2017-08-06 13:05
@mariokamenjak, yeah, perhaps we should think about some sort of Troubleshooting section and list such solutions there.

**Comment by mariokamenjak** [comment] 2017-08-06 13:08
Perhaps on one of the otter related sites.

**Comment by Emdek** [comment] 2017-08-06 13:13
@mariokamenjak, I'll think about something once I'll have some material, right now it would be just two entries. :-D
