### ISSUE TITLE
Bookmarks Manager defects

### ISSUE THREAD

**Issue by VSHY** [OtterBrowser/otter-browser#827] opened 2015-05-28 13:29 UTC
1. Menu items "Add bookmark" and "Edit bookmark" are creating an empty record when Cancel has been pressed in the bookmark dialog.
If to delete empty records then field "Folder" in "Add bookmark" and "Edit bookmark" dialogs are shown as ListBox with arrows...

2. The field "Folder" in "Add bookmark" dialog doesn't shown the last used folder (see Opera Presto).

3. Menu items "Edit bookmark" from the context menu on a page and from the main menu are both working wrong - they work as "Add bookmark" command:
• from the context menu on a page - "Add bookmark" dialog is shown, and one can add unlimited number of identical bookmarks;
• from the main menu - the check of unique messagebox from "Add bookmark" is shown.

4. The dialogs "Add bookmark"/"Edit bookmark" don't save their window size. It's very uncomfortable.

5. The Bookmarks Manager doesn't have the ability to select several bookmarks or folders with Ctrl/Shift+click.

6. The key Del doesn't delete the selected bookmark or folder.

7. The key Esc doesn't work in bookmark search field (it should working as "delete filter"; see Opera Presto).
The same is applied to all the windows (Managers) in the side panel.

8. The menu item "Add bookmark" is not in the folders of the Bookmarks Manager. With it is very easy to create a bookmark.

9. If to delete the bookmark then the corresponding item of the context- or main menu doesn't updated: the "Edit bookmark" is shown (it should be the "Add bookmark").

10. The folders are shown lower than the bookmarks. Additional setting for this is needed.

11. If to switch language then names of the folders aren't shown; one need to restart the browser.

**Comment by Felipefpl** [comment] 2015-05-29 00:59
12. When bookmarks are imported they arent organized by alphabetical order.

13. There arent colums like "Name" "Nickname" and "Address" (Opera 12 has them) at bookmarks manager to organize your bookmarks in the order you wish.

**Comment by Emdek** [comment] 2015-05-31 13:34
Duplicate of #297, related ticket: #128.
No need to copy missing issues, this ticket will be automatically referenced in original one.

**Closed by Emdek** 2015-05-31 13:34 UTC
Labels: duplicate

**Comment by VSHY** [comment] 2015-06-05 10:32
There are many more problems than in #297.
Was fixed point 1 only.

Extra - crash with 100% of reproduce:
1. Open any site (that is not in the bookmarks).
2. Add bookmark from the context menu on the page.
3. Open Bookmarks Manager, remove this bookmark and empty trash. Close Bookmarks Manager.
4. Close current site.
5. Open this site from the basket of the closed urls.
6. Edit bookmark from the context menu on the page (see point 9 in this ticket).
The result - crash.

**Comment by Emdek** [comment] 2015-10-12 10:51
@VSHY, most of these issues should be fixed now or have own tickets (multi selection, dialog sizes).

> The folders are shown lower than the bookmarks. Additional setting for this is needed.

What do you mean by that?

**Comment by VSHY** [comment] 2015-10-17 11:50
@Emdek 
In the Opera Presto, folders are placed on top, on bottom - bookmarks. And it conveniently.

I think that some settings needed for this: "sorted" (i.q. in Opera) and "unsorted" (i.q. in Otter now).
For "sorted" - to prohibit drug&droop of bookmarks.
For "unsorted" - to add ability to sort bookmarks manually.

**Comment by Emdek** [comment] 2015-10-17 21:16
@VSHY, I guess that it is feature mentioned in comments of original ticket, right?

**Comment by VSHY** [comment] 2015-10-19 10:25
@Emdek, somewhere about :)
