### ISSUE TITLE
new tab opened with JavaScript link not displaying properly

### ISSUE THREAD

**Issue by midluk** [OtterBrowser/otter-browser#1245] opened 2017-01-23 13:44 UTC
Opening new tabs with links containing JavaScript (which then actually opens the new tab) does not work properly.
A new tab opens, but the address bar and content of the previously active tab is shown (any links used in this new tab open in the tab of which the content is shown). Selecting "Detach Tab" from the tab bar detaches the tab and lets it display its content properly.

For example the "Hilfe- Import" link on https://gridka-ca-sec.fzk.de/ :
1. open any page in a tab
2. open https://gridka-ca-sec.fzk.de in a second tab
3. click the "Hilfe- Import" link
 ->Watch the new tab open but display a copy of the second tab
4. switch to tab 1
5. switch to tab 3
 -> see the new tab now display the content of tab 1
6. use a link in tab 3
 -> see tab 1 activate and follow the link
7. use "Detach Tab" on tab 3
 -> a new window opens and the proper content of tab 3 is shown

This is on Linux x86_64 with qt 5.7.1, QtWebKit (legacy) backend and current otter git master.

**Comment by midluk** [comment] 2017-01-29 09:53
BTW: If I disable the "Open new windows in a new tab instead" option, I get a new window with a not-maximized tab displaying properly.

**Comment by midluk** [comment] 2017-01-29 10:04
I updated to current git master and it seems like the original described bug is no longer reproducible. I now get a non-maximized free floating tab in the original window (displaying properly) like I think it is supposed to happen.
If I close the new tab and then reclick the link however, the requested size does not seem to be set correctly. The tab is still free floating in the original window, but it fills the complete window and not just part of it

**Comment by midluk** [comment] 2017-01-30 10:46
On my second computer (the one I originally reported the bug on) I can still reproduce the originally described bug with current git master. Not sure what is the difference, all library versions and used desktop environment should be identical. Tonight I will try to copy over the otter configuration directory between the computers and see if that causes the difference.

**Comment by midluk** [comment] 2017-01-30 20:05
I guess this is some race condition. On my slow computer it never works, on my faster computer it only sometimes fails.

And I noticed that after the link has been used, any new tab opened afterwards does not get keyboard focus in the address bar.

**Comment by Emdek** [comment] 2017-01-31 07:39
@midluk, so what is the current issue, just invalid sizing (I've seen that several times in the past) or something more?

**Comment by midluk** [comment] 2017-02-01 12:47
@Emdek,
I now guess that the differences I'm seeing between my two computers is caused by differences in the internet connection. My desktop computer and my notebook at home (45ms ping to the server) show different behavior than (the same) notebook at work (20ms ping to the server). However, saving the pages to files and loading them locally (i.e. extremely fast connection) does not make any difference at home.

On my desktop (and also on my notebook if I use it at home):
- Very seldom the originally described display issue
- Size problem on any link usage after the first one
- New tabs no longer focus the address bar after link usage
- On the first link usage if there is (exactly) one additional tab open, the visible background tab that is half covered by the new tab is not the tab with the link but the other tab

On my notebook at work (faster connection):
- The originally described display issue

**Comment by Emdek** [comment] 2017-02-01 13:52
@midluk, thanks for description, it should make it easier to reproduce it once I'll have some free time.

**Comment by midluk** [comment] 2017-03-05 22:57
I'm still consistently seeing this at work for different servers. I guess the transparent web filter proxy we have might be responsible for the difference I see between home and work.
I'm also consistently (at home and at work) seeing the "New tabs no longer focus the address bar after link usage" part of this issue.

**Comment by midluk** [comment] 2017-03-06 12:14
I just noticed that if I hover over one of the "not displaying properly" tabs in the tab bar (notebook at work), the thumbnail properly shows the tab content. So the page seems to be loaded and rendered, but just not displayed properly.

**Comment by midluk** [comment] 2017-04-19 21:04
The "New tabs no longer focus the address bar after link usage" part of the issue seems to be fixed with current master.
I'm however still seeing the display issue on my notebook.

**Comment by Emdek** [comment] 2017-04-28 09:25
@midluk, any other changes when using current master / weekly 173?

**Comment by midluk** [comment] 2017-04-28 14:12
I can't reproduce the display issue any longer. It seems to be either fixed or something changed on the network which makes this now behave identical between work and home. Did you make some changes that make you expect this to be fixed?

Address bar focus issue still seems fixed.

The new tab now always opens maximized. I guess the intention of the page I linked in the original reproduction steps is to open the page in a non-maximized new window. When "Open new windows in a new tab instead" is not checked, the new window (and tab) is still maximized. I also see #1239 then.

**Comment by Emdek** [comment] 2017-04-28 17:38
@midluk, yeah, there was at least one change that could affect display issue.

So right now there still seems to be issues with geometry of popups?

**Comment by Emdek** [comment] 2017-04-28 18:42
Sizing issue seems to be QtWebKit bug, it seems to ignore values (680 x 700).

**Comment by midluk** [comment] 2017-04-30 16:40
Yeah. seems to be just the size issue left. For new windows I can see the use in being opened non-maximized, but for tabs I think always opening as maximized might even be preferable.
BTW, I meant #1354 in my last comment.

**Comment by Emdek** [comment] 2017-05-08 20:20
Closing since sizing is upstream issue without a way to workaround it.
Hopefully it will be improved in near future.

**Closed by Emdek** 2017-05-08 20:20 UTC
Labels: bug, component: QtWebKitBackend, upstream issue

**Comment by midluk** [comment] 2017-05-18 16:37
The original display issue reappeared with revision 14779cfe50926f8c56ef927c029373c55ce6ead4 .
The issue is not present directly after starting otter, but appears only after a link on the start page has been used.
