### ISSUE TITLE
Findbar should be configurable 

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#888] opened 2015-07-16 22:07 UTC
Findbar should be configurable, at best in toolbars.json and by right-click too. As a minimum, it should be possible to set the icon sizes.

And where does the background color for the search term come from? Can it be made configurable too?

**Comment by Emdek** [comment] 2015-08-09 20:53
It can be considered duplicate of #825 (from code point of view they are almost the same).
That color has won ticket: #537.

**Closed by Emdek** 2015-08-09 20:53 UTC
Labels: duplicate
