### ISSUE TITLE
Start Page | Edit (context menu) only applies to the first Tile

### ISSUE THREAD

**Issue by NokTham** [OtterBrowser/otter-browser#857] opened 2015-06-14 22:26 UTC
On the Start Page, the option to edit Tiles properties, only applies to the first Tile.

https://dl.dropboxusercontent.com/s/ikdfbz8i4aetuzt/2015-06-14_23-23-40.mp4?dl=0

Otter 0.9.07 Weekly 75
Windows 7 64-bit

**Comment by Emdek** [comment] 2015-06-15 19:47
Duplicate of #853.

**Closed by Emdek** 2015-06-15 19:47 UTC
Labels: duplicate
