### ISSUE TITLE
Improve the side panel interface

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1011] opened 2015-12-01 18:50 UTC
Currently, to display the side panel, there is two ways:

1. to press F4,
2. to configure the tool bar to display the button and click it (it is also possible to display the panel selector).

See below what the second way looks like:

![Graphical display of panels](https://cloud.githubusercontent.com/assets/2029853/11510007/b6a00d9c-9861-11e5-9a73-7d24cdc81f25.png)

The result is not great:

* The selector appears **three times** and two of them are identical. Even without the added buttons, there is still two selectors.
* The added button and the selector are way too wide.

The very first thing to do is to display the selector only one time. I think that we should keep only the drop-down list, hence we could delete the column with icons, saving a lot of space. Then, the icon to add a panel could be replaced by an entry in the list.

To narrow the added selector and button, I propose to mix the button and the selector. In fact, only the selector remains but when clicking on an element, it displays the panel instead of just selecting the panel to be displayed with the button. To make the display faster for users, double clicking on the selector (without clicking on an entry) would be equivalent to open the “default” panel. When the panel is hidden, only the icon and the little arrow are displayed in the toolbar but the text is displayed in the drop-down menu.

When the panel is open, the text is displayed after the icon, plus the button to open the full-screen interface (green arrow on the picture) and the close button. The close button hides the panel and the selector lets the user to change the panel. What I am trying to explain looks like what the GTK library does with client-side decorations, here with Gedit:

![Gedit panel switcher](https://cloud.githubusercontent.com/assets/2029853/11510426/fea605cc-9863-11e5-98a4-147c98112741.png)

Like in GTK, all the selector interface would stay in the toolbar and the content would be the only thing outside (it may be easier to theme it because no ugly gap would be possible like it sadly was on Opera 12). Of course, we would need a vertical separator.

Here is a full view of Gedit with side panel, showing what it would be like:

![Gedit with side panel](https://cloud.githubusercontent.com/assets/2029853/11510566/94e9244c-9864-11e5-910c-dfbd26b61b3a.png)

**Comment by lollox** [comment] 2015-12-02 14:01
It's a bit that I don't follow how things are going on here, but what you're asking for has already been asked in a better way: let users to customize the GUI how they want. So if you want to remove the vertical toolbar of side panel (that is instead what I absolutely want, with the toggle edge too) you can do it without forcing other users to have the same setup. Exactly as in the glorious Opera.

So I suppose this is a duplicate and can be closed.

**Comment by pierreporte** [comment] 2015-12-02 18:21
I agree with you on the point that users should be able to customise the interface. However, this doesn’t mean that the default interface can’t be improved. As for the vertical toolbar, it could be part of the options.

**Comment by Emdek** [comment] 2015-12-14 21:48
@pierreporte, it's duplicate of #714.
I'm planning to overhaul our handling of sidebars completely, although I'm not convinced that we should change that much defaults.
For sure it will be possible to customize them.

**Closed by Emdek** 2015-12-14 21:48 UTC
Labels: duplicate
