### ISSUE TITLE
Suggestion: use Appimages instead of weekly builts for various distros

### ISSUE THREAD

**Issue by msjasinski** [OtterBrowser/otter-browser#1174] opened 2016-09-04 22:52 UTC
I've just learnt about AppImageKit: "Using (...) you can package desktop applications as AppImages that run on common Linux-based operating systems, such as RHEL, CentOS, Ubuntu, Fedora, debian and derivatives. http://appimage.org"). I think it is a good solution for Otter. Obviously, weekly Linux releases are not working, especially RPMs. Maybe this method would be better? Krita and some other packages are using it already.

**Comment by Emdek** [comment] 2016-09-05 08:18
Duplicate of #1148.

**Closed by Emdek** 2016-09-05 08:18 UTC
Labels: duplicate
