### ISSUE TITLE
Can't Reszie Filename Column In Download Sidebar

### ISSUE THREAD

**Issue by opticyclic** [OtterBrowser/otter-browser#784] opened 2015-04-08 05:01 UTC
All of the columns in the Download Sidebar can be resized apart from the Filename column.
The same applies to the Transfers Manager (probably the same component displayed in 2 different places)

**Comment by Emdek** [comment] 2015-04-08 18:00
Duplicate of #366.

**Closed** 2015-04-09 19:21 UTC
Labels: duplicate
