### ISSUE TITLE
Trimmed button labels in the Preferences

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#959] opened 2015-10-15 19:18 UTC
In the Preferences window, the labels of some buttons are too close to the border. This can easily be fixed by making the window a few pixels wider.

![screenshot-otter_15102015-214719](https://cloud.githubusercontent.com/assets/6757832/10524407/071a3a3a-7388-11e5-8fff-09f74bf215fd.jpg)

**Comment by Emdek** [comment] 2015-10-16 14:36
Duplicate of #917.

**Closed by Emdek** 2015-10-16 14:36 UTC
Labels: duplicate
