### ISSUE TITLE
problems in Gmail (loading time, switching "maillists")?

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#737] opened 2015-03-12 12:39 UTC
Hi all,
I recently noticed some problems while using Gmail in Otter - after opening the main page the data transfer bar is shown for a rather long time and some data appear to be loaded (or attempted to).
It is also not possible do display the "folder" content (or labeled maillist) by clicking on a label name. - most of the time nothing happens after clicking there; e.g.:
Interstentingly, pasting a copied URL works, e.g.:  https://mail.google.com/mail/#sent

Sometimes, but not quite regularly, an error message is shown in the console on such occasions:
Blocked a frame with origin "https://apis.google.com" from accessing a frame with origin "https://mail.google.com". Protocols, domains, and ports must match.

I am not sure, whether some individual setting may possibly interfere with this; it certainly seems unusual, that this hasn't been noticeda and repoorted already (unless I missed something).
(Otter 0.9.05. weekly 62; 32bit, win7)

regards,
    vbr

**Comment by Emdek** [comment] 2015-03-24 17:09
Are you using content blocking?
Is there any difference after changing User Agent to Chrome?

**Comment by vbr** [comment] 2015-03-24 21:26
Hi,
the content blockin was not active, but it doesn't seem to influence this (the behaviour doesn't change after activating some blocking filters).

Changing user agent doesn't help here either.
It is well possible, that there is something weird in my settings, but I couldn't identify anything relevant.
In Gmail, the links for the labels are somehow ignored in my Otter - after clicking on the them, the address in the address bar doesn't change and the page stays as is and the progress bar keeps showing 0B/s ....
 It is however possible to open such labeled pages such as
https://mail.google.com/mail/#sent
in new panel (via context menu or clicking the mousewheel, or after pasting and opening the link adress to a new empty panel); however in the first panel which is busy loaging gmail already, there won't load another gmail page even via address bar.
I hope, the description somehow makes sense. If there are any areas, I should check my settings or test something, please let me know.

regards,
   vbr

**Comment by Emdek** [comment] 2015-03-26 13:46
@vbr, it's duplicate of #723, side effect of 95646a4ac07c20ccc00d705533906005ba066729.

**Closed by Emdek** 2015-03-26 13:46 UTC
Labels: needs info
