### ISSUE TITLE
support Pepper API

### ISSUE THREAD

**Issue by DI555** [OtterBrowser/otter-browser#908] opened 2015-07-30 00:07 UTC
I don't know... may be it's an upstream...but could be really great if Otter could support pepper api!

**Comment by The-Compiler** [comment] 2015-07-30 09:06
Yep, that's the responsibility of the engine - QtWebKit never will support PPAPI, and I believe QtWebEngine will starting with the Qt 5.6 version (at least for flash): [change](https://codereview.qt-project.org/#/c/104669/)

**Comment by Emdek** [comment] 2015-07-30 13:19
Duplicate of #221.

**Closed by Emdek** 2015-07-30 13:19 UTC
Labels: duplicate
