### ISSUE TITLE
Option for own default Search of Speed Dial

### ISSUE THREAD

**Issue by VSHY** [OtterBrowser/otter-browser#943] opened 2015-09-12 10:38 UTC
In the search engine preferences of Opera Presto there are two checkboxes: "Use as default search engine" and "Use as Speed Dial search engine".
The same in Otter would be preferable.

**Comment by Emdek** [comment] 2015-10-09 20:49
Duplicate of #897.

**Closed by Emdek** 2015-10-09 20:49 UTC
Labels: duplicate
