### ISSUE TITLE
LRU tab switching via Ctrl-Tab

### ISSUE THREAD

**Issue by vitalif** [OtterBrowser/otter-browser#52] opened 2014-01-11 11:19 UTC
Hi!
One of the basic features of Opera is LRU tab switching out of the box.
I'm not sure if you've already implemented keyboard shortcuts in otter (all controls on keyboard page in preferences are grayed), but for me Ctrl-Tab works very strange - when I press it, otter does not switch tabs, but the current tab becomes gray as if the web view with address bar and everything was removed. It seems like a bug to me :-)

**Comment by landroni** [comment] 2015-01-01 00:23
Works for me. Thanks!

**Comment by komoku** [comment] 2015-01-28 16:23
Wouldn't this feature come "for free" with MDI? I think MDI window managers know the order in which windows were used (it's the order they use to draw them on screen, so that recent windows appear on top of older ones).

This is why with the "click on tab to minimize" option in the old Opera, if you click the active tab, you automatically go to the last recently used tab, a really good feature IMO because you dont' even need to use the keyboard to go to the last recently used tab.

**Comment by Emdek** [comment] 2015-01-28 22:06
@komoku, not in the way we want it.
`QTabBar` stores that data for own purposes (to decide what to do after closing active tab) but doesn't expose it.
Also, we can't rely on it if we want to make it completely optional (not just allow to hide it).

**Closed** 2015-02-28 21:31 UTC
Labels: enhancement, severity: high priority

**Comment by ersi-dnd** [comment] 2015-03-01 09:06
Thanks for this one. Works pretty well in full screen mode and allows selecting tabs with mouse too, almost like in Opera.

The thing is that this function renders the tabbar largely obsolete, at least for those who don't need tab stacking. Therefore it would make sense to implement now #702 too :)

**Comment by Emdek** [comment] 2015-03-01 11:07
@ersi-dnd, most of differences are intentional (maybe except lack of multi column support, hopefully someone will come up with good algorithm to handle it nicely, someday) to make it indeed a replacement for tab bar, so it won't close after mouse interaction.
I'll add some more details here, like ability to close tabs using small close button visible on hover etc.
BTW, I think it could be a good idea to allow to set a shortcut to show it directly.

#702 will be done as part of #31, current approach is unreliable and not worth adding more workarounds, it needs to be done properly.

**Comment by vitalif** [comment] 2015-03-04 22:22
Thanks, just tested it. I have an issue - sometimes the tab switcher shows up, but it doesn't switch the tab from the current one. It seems it happens when I'm pressing ctrl and tab too fast... almost simultaneously...? Can you try and check? I can post a screencast if it helps you.

**Comment by Emdek** [comment] 2015-03-09 19:49
@vitalif, yeah, screencast could be useful, so far I couldn't reproduce that.

**Comment by vitalif** [comment] 2015-03-09 20:58
In fact I'm not sure it will help, but...
http://vmx.yourcmc.ru/var/screencast/otter_badswitching.flv

**Comment by Emdek** [comment] 2015-03-17 08:49
@vitalif, I've managed to reproduce it few times, it looks like a race condition, key release event being fired before tab gets selected.

Currently I'm considering different strategy for such cases, completely skipping dialog if Control will be released sooner than ~100 milliseconds since key press event.
KWin seems to use similar strategy for Alt+Tab switcher.

**Comment by lc-guy** [comment] 2015-12-12 18:24
1 and 2 aren't very convenient. If the previous/current tab currently has a form highlighted, it will not be able to switch tabs.

Why not leave ctrl-tab and ctrl-shift-tab's default behaviour? Alternatively, provide a way to make its behaviour equal to other browsers'.

**Comment by vitalif** [comment] 2015-12-12 21:11
F1/F2 are good.
1/2 is just a habit after using Opera for a long time.)

**Comment by xploSEoF** [comment] 2015-12-14 08:18
@lc-guy: ctrl+tab should follow the standard behaviour - switch through the tabs in "most recently used" order. This is the way alt+tab works in the OS, and ctrl+tab works in other applications (just not Chrome and Firefox).

The reason behind this is simple: Chrome and Firefox were only really designed for a dozen or so tabs, not too many to cycle through the lot. Operating systems are designed for a lot more applications at once, and most applications that have "tabs" are designed for a lot more tabs than Chrome and Firefox. As such, switching between most recently used is... logical.

Worth noting here, Opera 12.x was designed to handle a hell of a lot of tabs, and they chose the most recently used method - and it looks like Otter will follow many of the same decisions.

If you wish to cycle through the tabs in their display order, then you can override (in the keyboard shortcuts) or use 1+2.
