### ISSUE TITLE
[Windows] updater for Otter

### ISSUE THREAD

**Issue by lollox** [OtterBrowser/otter-browser#661] opened 2015-01-15 21:44 UTC
UPDATE: For the latest version that fix all problems of previous version, please refer to @uahim message below: https://github.com/OtterBrowser/otter-browser/issues/661#issuecomment-72558101 or go to http://thewilderness.bplaced.net/otter-updater/

I'll leave this message for legacy infos only  ;)
##################################################
WARNING: the program has been rewritten and new version, targeted as 1.0, has been released on 17/01/2015. If you downloaded it before you should download the new version ;) (you can use the md5 checksum to be sure)

Hi

I just created a small updater to automatize the process of download the latest build from Sourceforge and "install" it. It's a small .bat script that uses command line versions of wget and 7zip to achieve the result, all packed in a tiny executable (really a self extracting 7zip archive).

All you've to do is putting the "updater.exe" executable in the folder you want to install Otter (or where Otter is already installed), launch it and wait to have you browser updated. At the end of process Otter will be launched. 

In the script I used lot of controls to be sure nothing will go wrong, but if you find any bug or weird behaviors please post your feedbacks.

If you want to analyze it, I remember you that it's a simple self extracting archive so you can do what you want. And if you add some interesting modification you can always share it with us ;)

OK that's all. The new version should not have any problem with antivirus softwares ( https://www.virustotal.com/it/file/cfedab95fdeb9e04169a4a3cd0f9831f9a00dc2ffa81b377cd0318461d39566d/analysis/1421527484/ ), but if your AV alerts you please post here your feedback.

And finally the link to download:
EDIT: refer to @uahim post below

Thanks for your attention. Enjoy ;)

**Comment by lollox** [comment] 2015-01-17 20:42
NEW VERSION 1.0 available! Please read the first post!

**Comment by uahim** [comment] 2015-01-19 14:53
nice idea!

do I understand it right that it doesn't check which version is installed, i.e. it starts downloading immediately? which means it "updates" regardless of the fact that the latest version is already installed?

also, did you know that TIMEOUT isn't available on older systems? you could include the tiny exe in the package, or use (and include) SLEEP from the Win 2003 resource kit

**Comment by lollox** [comment] 2015-01-19 17:19
Hi

yes it always downloads the latest build and install it since sadly I was not able to find a way for version checking (I'm not a programmer)

About TIMEOUT I don't know... Windows 9x is a very old system nowadays and runs only on very old PCs, while Otter is based on the WebKit engine that isn't really usable on old machines (and when it will switch to Chromium it will be even worse, I suppose)

However I will have a look at it

**Comment by uahim** [comment] 2015-01-19 20:21
@lollox I think got a quick and very dirty solution to check vor the version before downloading, which is also portable to shellscript for linux/*nix systems. as there is no way of direct messageing here on github, just email me ( findnoenemy AT web DOT de) if you want :)

**Comment by Emdek** [comment] 2015-01-19 21:02
Uhm, it's kind of duplicate of #92. ;-)

**Comment by uahim** [comment] 2015-01-19 21:24
@Emdek nice, I didn't see this. of course a built-in updater is better than any other solution, but until then...

**Comment by Emdek** [comment] 2015-01-19 21:37
@uahim, sure, this is why this one wasn't closed, as they aren't exactly the same. ;-)

**Comment by lollox** [comment] 2015-01-20 11:24
@Emdek yes, I initiallywrote it just for my use (waiting for a good integrated AUTOupdate system) and only in a second time I shared here .... to be honest I hope this tool will become useless as soon as possible ;)

@uahim : you have mail ;)

**Comment by uahim** [comment] 2015-02-02 23:05
here's my version, Otter updater for Windows 32/64
http://thewilderness.bplaced.net/otter-updater/

only downloads and installs if a newever version is available, updates itself if necessary, remembers settings and asks the user on 64bit systems which version to install. tested on Win7 64bit and WinXP 32bit

**Comment by uahim** [comment] 2015-08-31 20:57
https://github.com/OtterBrowser/otter-browser/issues/92
so this can be closed, then? I also added a note on my updater page

**Comment by Emdek** [comment] 2015-08-31 21:04
@uahim, I guess.

Thanks for this initiative. :-)

**Closed by Emdek** 2015-08-31 21:04 UTC
Labels: discussion
