### ISSUE TITLE
Crash on Ctrl+U

### ISSUE THREAD

**Issue by VSHY** [OtterBrowser/otter-browser#873] opened 2015-07-07 09:02 UTC
Open any webcite and press Ctrl+U. Result: crash.
Win7 64-bit. Otter 78-build 32-bit.

**Comment by ersi-dnd** [comment] 2015-07-07 11:36
Cannot confirm. 

Do you have Ctrl+u assigned to some action? In Mozillas it's assigned to source viewer. I opened up the source viewer from menu. No crash with source viewer. No crash with Ctrl+u.

**Comment by VSHY** [comment] 2015-07-07 12:02
I didn't change this hotkey. It should open the source viewer, you are right.
In my case the crash occurs and from context menu too.

**Comment by Emdek** [comment] 2015-07-07 12:42
@VSHY, cannot reproduce so far, I've checked it on 64 bit Linux and 32 bit Windows 7.

**Comment by VSHY** [comment] 2015-07-07 14:23
@Emdek 
Maybe I should send some Otter-settings?

**Comment by Emdek** [comment] 2015-07-13 17:55
@VSHY, nah, it shouldn't be affected by any of settings.
Backtrace would be useful, although it could be harder to generate it under Windows.

**Comment by VSHY** [comment] 2015-07-15 11:08
Microsoft (R) Windows Debugger Version 10.0.10075.9 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

*** wait with pending attach
Symbol search path is: *** Invalid ***
****************************************************************************
* Symbol loading may be unreliable without a symbol search path.           *
* Use .symfix to have the debugger choose a symbol path.                   *
* After setting your symbol path, use .reload to refresh symbol locations. *
****************************************************************************
Executable search path is: 
ModLoad: 00000000`00400000 00000000`007a7000   C:\Portable\Otter\otter-browser.exe
ModLoad: 00000000`76e60000 00000000`77009000   C:\Windows\SYSTEM32\ntdll.dll
ModLoad: 00000000`77040000 00000000`771c0000   ntdll.dll
ModLoad: 00000000`732a0000 00000000`732df000   C:\Windows\SYSTEM32\wow64.dll
ModLoad: 00000000`73240000 00000000`7329c000   C:\Windows\SYSTEM32\wow64win.dll
ModLoad: 00000000`73230000 00000000`73238000   C:\Windows\SYSTEM32\wow64cpu.dll
ModLoad: 00000000`74e00000 00000000`74f10000   KERNEL32.dll
ModLoad: 00000000`76bf0000 00000000`76c37000   KERNELBASE.dll
ModLoad: 00000000`68880000 00000000`68dae000   Qt5Core.dll
ModLoad: 00000000`76690000 00000000`76731000   ADVAPI32.dll
ModLoad: 00000000`74a10000 00000000`74abc000   msvcrt.dll
ModLoad: 00000000`762a0000 00000000`762b9000   SECHOST.dll
ModLoad: 00000000`76090000 00000000`76180000   RPCRT4.dll
ModLoad: 00000000`749b0000 00000000`74a10000   SspiCli.dll
ModLoad: 00000000`749a0000 00000000`749ac000   CRYPTBASE.dll
ModLoad: 00000000`6e940000 00000000`6e964000   libgcc_s_dw2-1.dll
ModLoad: 00000000`64940000 00000000`64954000   libwinpthread-1.dll
ModLoad: 00000000`72e10000 00000000`72e22000   MPR.dll 
ModLoad: 00000000`762c0000 00000000`7641c000   ole32.dll
ModLoad: 00000000`76b60000 00000000`76bf0000   GDI32.dll
ModLoad: 00000000`76190000 00000000`76290000   USER32.dll
ModLoad: 00000000`76060000 00000000`7606a000   LPK.dll 
ModLoad: 00000000`75b60000 00000000`75bfd000   USP10.dll
ModLoad: 00000000`74f10000 00000000`75b5b000   SHELL32.dll
ModLoad: 00000000`75c10000 00000000`75c67000   SHLWAPI.dll
ModLoad: 00000000`74ae0000 00000000`74b15000   WS2_32.dll
ModLoad: 00000000`76080000 00000000`76086000   NSI.dll 
ModLoad: 00000000`6fc40000 00000000`6fd41000   libstdc++-6.dll
ModLoad: 00000000`61940000 00000000`61e60000   Qt5Gui.dll
ModLoad: 00000000`6b480000 00000000`6b54a000   Qt5Multimedia.dll
ModLoad: 00000000`69700000 00000000`6987f000   Qt5Network.dll
ModLoad: 00000000`74be0000 00000000`74d01000   CRYPT32.dll
ModLoad: 00000000`76290000 00000000`7629c000   MSASN1.dll
ModLoad: 00000000`70ab0000 00000000`70af4000   DNSAPI.dll
ModLoad: 00000000`6df40000 00000000`6dfa0000   Qt5PrintSupport.dll
ModLoad: 00000000`74b20000 00000000`74b9b000   COMDLG32.dll
ModLoad: 00000000`6dff0000 00000000`6e074000   COMCTL32.dll
ModLoad: 00000000`6ed30000 00000000`6ed81000   WINSPOOL.DRV
ModLoad: 00000000`00bb0000 00000000`011f5000   Qt5Widgets.dll
ModLoad: 00000000`62740000 00000000`6297e000   Qt5Script.dll
ModLoad: 00000000`6e080000 00000000`6e0b2000   WINMM.dll
ModLoad: 00000000`6d7c0000 00000000`6d807000   Qt5Sql.dll
ModLoad: 00000000`65c80000 00000000`67c5e000   Qt5WebKit.dll
ModLoad: 00000000`72f40000 00000000`72f49000   VERSION.dll
ModLoad: 00000000`63c40000 00000000`63f07000   icuin54.dll
ModLoad: 00000000`01200000 00000000`013c5000   icuuc54.dll
ModLoad: 00000000`013d0000 00000000`02c0d000   icudt54.dll
ModLoad: 00000000`02c10000 00000000`03026000   Qt5Qml.dll
ModLoad: 00000000`03030000 00000000`033c3000   Qt5Quick.dll
ModLoad: 00000000`64b80000 00000000`64bc5000   Qt5Positioning.dll
ModLoad: 00000000`70cc0000 00000000`70cf7000   Qt5Sensors.dll
ModLoad: 00000000`6a000000 00000000`6a026000   Qt5WebChannel.dll
ModLoad: 00000000`00320000 00000000`0036c000   Qt5WebKitWidgets.dll
ModLoad: 00000000`00370000 00000000`003ca000   Qt5OpenGL.dll
ModLoad: 00000000`6c5c0000 00000000`6c5e0000   Qt5MultimediaWidgets.dll
ModLoad: 00000000`62a40000 00000000`62a83000   Qt5WinExtras.dll
ModLoad: 00000000`74d10000 00000000`74d70000   IMM32.dll
ModLoad: 00000000`76810000 00000000`768dc000   MSCTF.dll
ModLoad: 00000000`705e0000 00000000`70612000   nvinit.dll
ModLoad: 00000000`72f50000 00000000`72fc3000   guard32.dll
ModLoad: 00000000`75c70000 00000000`75c75000   PSAPI.DLL
ModLoad: 00000000`72f30000 00000000`72f37000   FLTLIB.DLL
ModLoad: 00000000`6a880000 00000000`6a9e4000   qwindows.dll
ModLoad: 00000000`768e0000 00000000`7696f000   OLEAUT32.dll
ModLoad: 00000000`052d0000 00000000`05350000   UxTheme.dll
ModLoad: 00000000`6bad0000 00000000`6bada000   pshook.dll
ModLoad: 00000000`74bb0000 00000000`74bdb000   imagehlp.dll
ModLoad: 00000000`10000000 00000000`1004e000   FileBXH.dll
ModLoad: 00000000`705b0000 00000000`705c3000   dwmapi.dll
ModLoad: 00000000`70a00000 00000000`70a18000   qdds.dll
ModLoad: 00000000`61f00000 00000000`61f11000   qgif.dll
ModLoad: 00000000`6c600000 00000000`6c615000   qicns.dll
ModLoad: 00000000`6e840000 00000000`6e852000   qico.dll
ModLoad: 00000000`6d440000 00000000`6d4cd000   qjp2.dll
ModLoad: 00000000`626c0000 00000000`62705000   qjpeg.dll
ModLoad: 00000000`69240000 00000000`692a3000   qmng.dll
ModLoad: 00000000`053c0000 00000000`053d0000   qsvg.dll
ModLoad: 00000000`054d0000 00000000`05528000   Qt5Svg.dll
ModLoad: 00000000`6b640000 00000000`6b650000   qtga.dll
ModLoad: 00000000`6cf00000 00000000`6cf72000   qtiff.dll
ModLoad: 00000000`053d0000 00000000`053e0000   qwbmp.dll
ModLoad: 00000000`056a0000 00000000`05703000   qwebp.dll
ModLoad: 00000000`6d340000 00000000`6d40b000   qsqlite.dll
ModLoad: 00000000`71e00000 00000000`71e4c000   SSLEAY32.dll
ModLoad: 00000000`71cc0000 00000000`71df9000   LIBEAY32.dll
ModLoad: 00000000`05ac0000 00000000`05bae000   MSVCR120.dll
ModLoad: 00000000`05530000 00000000`05538000   vlmshlp.dll
ModLoad: 00000000`70590000 00000000`705a7000   CRYPTSP.dll
ModLoad: 00000000`70550000 00000000`7058b000   RSAENH.dll
ModLoad: 00000000`72a90000 00000000`72ae8000   WINHTTP.dll
ModLoad: 00000000`72a40000 00000000`72a8f000   webio.dll
ModLoad: 00000000`72d80000 00000000`72d9c000   IPHLPAPI.DLL
ModLoad: 00000000`72d70000 00000000`72d77000   WINNSI.DLL
ModLoad: 00000000`729b0000 00000000`729bd000   dhcpcsvc6.DLL
ModLoad: 00000000`72990000 00000000`729a2000   dhcpcsvc.DLL
ModLoad: 00000000`72950000 00000000`72958000   CREDSSP.dll
ModLoad: 00000000`75ee0000 00000000`75f07000   CFGMGR32.dll
ModLoad: 00000000`72910000 00000000`7294c000   MSWSOCK.dll
ModLoad: 00000000`72970000 00000000`72975000   WSHTCPIP.dll
ModLoad: 00000000`72960000 00000000`72966000   WSHIP6.dll
ModLoad: 00000000`728a0000 00000000`728a6000   rasadhlp.dll
ModLoad: 00000000`09340000 00000000`09378000   fwpuclnt.dll
ModLoad: 00000000`74310000 00000000`7431e000   RpcRtRemote.dll
(820.918): Break instruction exception - code 80000003 (first chance)
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\Windows\SYSTEM32\ntdll.dll - 
ntdll!DbgBreakPoint:
00000000`76eace30 cc              int     3
0:018> g
ModLoad: 00000000`0cd20000 00000000`0d96b000   C:\Windows\SysWOW64\shell32.dll
ModLoad: 00000000`0cd20000 00000000`0d96b000   C:\Windows\SysWOW64\shell32.dll
ModLoad: 00000000`0cd20000 00000000`0d96b000   C:\Windows\SysWOW64\shell32.dll
ModLoad: 00000000`0cd20000 00000000`0d96b000   C:\Windows\SysWOW64\shell32.dll
ModLoad: 00000000`72970000 00000000`72975000   C:\Windows\SysWOW64\wshtcpip.dll
ModLoad: 00000000`72960000 00000000`72966000   C:\Windows\SysWOW64\wship6.dll
ModLoad: 00000000`094e0000 00000000`09518000   C:\Windows\SysWOW64\fwpuclnt.dll
ModLoad: 00000000`72970000 00000000`72975000   C:\Windows\SysWOW64\wshtcpip.dll
ModLoad: 00000000`72970000 00000000`72975000   C:\Windows\SysWOW64\wshtcpip.dll
ModLoad: 00000000`0cd20000 00000000`0d96b000   C:\Windows\SysWOW64\shell32.dll
ModLoad: 00000000`0cd20000 00000000`0d96b000   C:\Windows\SysWOW64\shell32.dll
ModLoad: 00000000`72970000 00000000`72975000   C:\Windows\SysWOW64\wshtcpip.dll
ModLoad: 00000000`72960000 00000000`72966000   C:\Windows\SysWOW64\wship6.dll
ModLoad: 00000000`09210000 00000000`09248000   C:\Windows\SysWOW64\fwpuclnt.dll
ModLoad: 00000000`72970000 00000000`72975000   C:\Windows\SysWOW64\wshtcpip.dll
ModLoad: 00000000`72960000 00000000`72966000   C:\Windows\SysWOW64\wship6.dll
ModLoad: 00000000`09210000 00000000`09248000   C:\Windows\SysWOW64\fwpuclnt.dll
(820.4c0): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
*** WARNING: Unable to verify timestamp for Qt5Widgets.dll
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for Qt5Widgets.dll - 
*** ERROR: Module load completed but symbols could not be loaded for C:\Portable\Otter\otter-browser.exe
Qt5Widgets!ZN7QWidget7setFontERK5QFont+0x9:
00bf0099 8b5904          mov     ebx,dword ptr [ecx+4] ds:002b:00000004=????????
0:000:x86> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

*** ERROR: Symbol file could not be found.  Defaulted to export symbols for ntdll.dll - 
*************************************************************************
***                                                                   ***
***                                                                   ***
***    Either you specified an unqualified symbol, or your debugger   ***
***    doesn't have full symbol information.  Unqualified symbol      ***
***    resolution is turned off by default. Please either specify a   ***
***    fully qualified symbol module!symbolname, or enable resolution ***
***    of unqualified symbols by typing ".symopt- 100". Note that   ***
***    enabling unqualified symbol resolution with network symbol     ***
***    server shares in the symbol path may cause the debugger to     ***
***    appear to hang for long periods of time when an incorrect      ***
***    symbol name is typed or the network symbol server is down.     ***
***                                                                   ***
***    For some commands to work properly, your symbol path           ***
***    must point to .pdb files that have full type information.      ***
***                                                                   ***
***    Certain .pdb files (such as the public OS symbols) do not      ***
***    contain the required information.  Contact the group that      ***
***    provided you with these symbols if you need this command to    ***
***    work.                                                          ***
***                                                                   ***
***    Type referenced: $ntdllsym!_CONTEXT                            ***
***                                                                   ***
*************************************************************************
***** OS symbols are WRONG. Please fix symbols to do analysis.

*********************************************************************
* Symbols can not be loaded because symbol path is not initialized. *
*                                                                   *
* The Symbol Path can be set by:                                    *
*   using the _NT_SYMBOL_PATH environment variable.                 *
*   using the -y <symbol_path> argument when starting the debugger. *
*   using .sympath and .sympath+                                    *
*********************************************************************
*********************************************************************
* Symbols can not be loaded because symbol path is not initialized. *
*                                                                   *
* The Symbol Path can be set by:                                    *
*   using the _NT_SYMBOL_PATH environment variable.                 *
*   using the -y <symbol_path> argument when starting the debugger. *
*   using .sympath and .sympath+                                    *
*********************************************************************
*************************************************************************
***                                                                   ***
***                                                                   ***
***    Either you specified an unqualified symbol, or your debugger   ***
***    doesn't have full symbol information.  Unqualified symbol      ***
***    resolution is turned off by default. Please either specify a   ***
***    fully qualified symbol module!symbolname, or enable resolution ***
***    of unqualified symbols by typing ".symopt- 100". Note that   ***
***    enabling unqualified symbol resolution with network symbol     ***
***    server shares in the symbol path may cause the debugger to     ***
***    appear to hang for long periods of time when an incorrect      ***
***    symbol name is typed or the network symbol server is down.     ***
***                                                                   ***
***    For some commands to work properly, your symbol path           ***
***    must point to .pdb files that have full type information.      ***
***                                                                   ***
***    Certain .pdb files (such as the public OS symbols) do not      ***
***    contain the required information.  Contact the group that      ***
***    provided you with these symbols if you need this command to    ***
***    work.                                                          ***
***                                                                   ***
***    Type referenced: nt!_CONTEXT                                   ***
***                                                                   ***
*************************************************************************
*********************************************************************
* Symbols can not be loaded because symbol path is not initialized. *
*                                                                   *
* The Symbol Path can be set by:                                    *
*   using the _NT_SYMBOL_PATH environment variable.                 *
*   using the -y <symbol_path> argument when starting the debugger. *
*   using .sympath and .sympath+                                    *
*********************************************************************
*********************************************************************
* Symbols can not be loaded because symbol path is not initialized. *
*                                                                   *
* The Symbol Path can be set by:                                    *
*   using the _NT_SYMBOL_PATH environment variable.                 *
*   using the -y <symbol_path> argument when starting the debugger. *
*   using .sympath and .sympath+                                    *
*********************************************************************
*********************************************************************
* Symbols can not be loaded because symbol path is not initialized. *
*                                                                   *
* The Symbol Path can be set by:                                    *
*   using the _NT_SYMBOL_PATH environment variable.                 *
*   using the -y <symbol_path> argument when starting the debugger. *
*   using .sympath and .sympath+                                    *
*********************************************************************

FAULTING_IP: 
Qt5Widgets!ZN7QWidget7setFontERK5QFont+9
00bf0099 8b5904          mov     ebx,dword ptr [ecx+4]

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 0000000000bf0099 (Qt5Widgets!ZN7QWidget7setFontERK5QFont+0x0000000000000009)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 0000000000000004
Attempt to read from address 0000000000000004

FAULTING_THREAD:  000004c0

BUGCHECK_STR:  556366F2

PROCESS_NAME:  otter-browser.exe

WRONG_SYMBOLS_TIMESTAMP: 556366f2

WRONG_SYMBOLS_SIZE: 1a9000

FAULTING_MODULE: 0000000076e60000 ntdll

DEBUG_FLR_IMAGE_TIMESTAMP:  556366f2

ADDITIONAL_DEBUG_TEXT:  
You can run '.symfix; .reload' to try to fix the symbol path and load symbols. ; Followup set based on attribute [Is_ChosenCrashFollowupThread] from Frame:[0] on thread:[PSEUDO_THREAD]

LAST_CONTROL_TRANSFER:  from 0000000000000000 to 0000000000000000

ANALYSIS_VERSION: 10.0.10075.9 amd64fre

STACK_TEXT:  
00000000`00000000 00000000`00000000 wrong_symbols!WRONG_SYMBOLS+0x0


STACK_COMMAND:  .ecxr ; kb ; ** Pseudo Context ** ; kb

SYMBOL_STACK_INDEX:  0

FOLLOWUP_NAME:  MachineOwner

EXCEPTION_CODE: (NTSTATUS) 0x556366f2 - <Unable to get error code text>

FAILURE_EXCEPTION_CODE:  556366F2

EXCEPTION_STR:  WRONG_SYMBOLS

IMAGE_NAME:  ntdll.wrong.symbols.dll

MODULE_NAME: ntdll_wrong_symbols

SYMBOL_NAME:  ntdll_wrong_symbols!556366F21A9000

BUCKET_ID:  WRONG_SYMBOLS_X64_6.1.7601.18869_(win7sp1_gdr.150525-0603)_TIMESTAMP_150525-181618

DEFAULT_BUCKET_ID:  WRONG_SYMBOLS_X64_6.1.7601.18869_(win7sp1_gdr.150525-0603)_TIMESTAMP_150525-181618

PRIMARY_PROBLEM_CLASS:  WRONG_SYMBOLS

FAILURE_PROBLEM_CLASS:  WRONG_SYMBOLS_X64_6.1.7601.18869_(win7sp1_gdr.150525-0603)_TIMESTAMP_150525-181618

FAILURE_IMAGE_NAME:  ntdll.wrong.symbols.dll

FAILURE_FUNCTION_NAME:  556366F21A9000

FAILURE_SYMBOL_NAME:  ntdll.wrong.symbols.dll!556366F21A9000

FAILURE_BUCKET_ID:  WRONG_SYMBOLS_X64_6.1.7601.18869_(win7sp1_gdr.150525-0603)_TIMESTAMP_150525-181618_556366F2_ntdll.wrong.symbols.dll!556366F21A9000

ANALYSIS_SOURCE:  UM

FAILURE_ID_HASH_STRING:  um:wrong_symbols_x64_6.1.7601.18869_(win7sp1_gdr.150525-0603)_timestamp_150525-181618_556366f2_ntdll.wrong.symbols.dll!556366f21a9000

FAILURE_ID_HASH:  {b671f84d-5db4-0eb3-cdf4-226131488dfe}

Followup:     MachineOwner
---------

**Closed** 2015-07-19 19:32 UTC
Labels: needs info

**Comment by Emdek** [comment] 2015-07-19 19:34
@VSHY, let me know if above change really fixes this issue for you.

**Comment by VSHY** [comment] 2015-07-24 09:12
@Emdek 
Crash was fixed. Thank you very much!
