### ISSUE TITLE
Page content is visible in other tabs

### ISSUE THREAD

**Issue by Type-kun** [OtterBrowser/otter-browser#816] opened 2015-05-16 19:03 UTC
1) Open http://www.kongregate.com/games/StudioCime/mu-complex-episode-two
2) Wait until the flash starts loading
3) Open any other tab, i.e. google page
4) This happens: http://puu.sh/hPCJe.png . What.

Similar things happen with other embedded plugins on other sites: http://superhotgame.com/play-prototype shows the same behavior. Tested on WinXP 32x, latest test build, happens at least since January.

**Comment by Emdek** [comment] 2015-05-16 20:59
That is known issue in QtWebKit under Windows, it is supposed to be fixed in Qt 5.5 which most likely will be used by next weekly (using beta packages, that should fix more stuff than break anyway ;-)).

Duplicate of #150.

**Closed by Emdek** 2015-05-16 20:59 UTC
Labels: duplicate
