### ISSUE TITLE
Select like a boss is missing

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#1439] opened 2017-10-21 23:05 UTC
Not sure how to call this feature, but in old Opera it was possible to start selecting in the middle of weblinks without any problem. Vivaldi has reimplemented this. In other browsers it's only doable in caret mode. Does Otter even have a caret mode?

**Comment by Emdek** [comment] 2017-10-22 07:37
Duplicate of #109.

**Closed by Emdek** 2017-10-22 07:37 UTC
Labels: duplicate
