### ISSUE TITLE
Download saved with over 220 letters as title

### ISSUE THREAD

**Issue by xmint** [OtterBrowser/otter-browser#886] opened 2015-07-13 04:53 UTC
windows bin version #79  When downloaded, a file from mega (Driver_Auto_Installer.zip) was saved  with a name over 220 letters long though with correct suffix. File seemed to have the correct size. 

(firefox downloaded the file with the correct filename).

**Comment by Emdek** [comment] 2015-08-10 19:24
Duplicate of #800.

**Closed by Emdek** 2015-08-10 19:24 UTC
Labels: duplicate
