### ISSUE TITLE
progress bar misplaced on initial page load in new tab

### ISSUE THREAD

**Issue by midluk** [OtterBrowser/otter-browser#1327] opened 2017-04-03 16:52 UTC
During initial page loads (until the main html file is loaded), the progress bar is not visible at the bottom but only partially at the top left. I can only see "ment: 0%    >". When the html file is loaded and all other content is fetched, the progress bar is properly visible at the bottom.
This happens if I use the address bar to manually insert the address in a new tab (no site previously loaded). This does not seem to happen from a bookmark or from a start page button or when there is already a page displayed.

This happens for some time now and also occurs with a new otter profile.

**Comment by Emdek** [comment] 2017-04-03 16:53
Duplicate of #1304.

**Closed by Emdek** 2017-04-03 16:53 UTC
Labels: duplicate

**Comment by midluk** [comment] 2017-04-03 17:26
I know having open one "I just mash 25 issues into one, so nobody finds them" issue looks better than having open 17 (some have already been fixed) separate issues. Even though this issue was created after your mash issue, it contains more information and is easier to find. Please reopen so this does not get lost with the next "please report everything again in a new mash report" action.

**Comment by Emdek** [comment] 2017-04-03 17:29
@midluk, don't worry, this one was already researched and simply waits in queue.
