### ISSUE TITLE
Generic mouse button actions

### ISSUE THREAD

**Issue by Emdek** [OtterBrowser/otter-browser#77] opened 2014-01-14 13:08 UTC
Currently there are available some (optional) mouse button actions for tab bar, like double click or middle click for tab close, but it might be not flexible enough for some users.

The idea is to allow to customize these actions for various contexts (for example: tab in tab bar, tab bar, link in page, page, other), by creating pairs of mouse button actions (left, right, middle, double click) and actions to be triggered (for example tab pinning on double click instead of closing it), possibly with addition of modifier (shift, alt or control).

Middle click on page (outside tab bar and not over link) could be used to enter auto scroll mode or go to link from clipboard etc.

These actions could be managed in a way similar to that planned for keyboard shortcuts and mouse gestures, by predefined profiles that could be enabled or disabled.

I've created similar system (but without contexts) for one of my Plasma applets:
http://im9.eu/picture/dh2981

Any comments? :-)

**Comment by vbr** [comment] 2015-09-09 08:16
Thanks for redirecting the issue #928 here; I think the mentioned problem is connected with some "shadowing" of the mouse gestures e.g. by performing a general page-gesture over a link element, where it is not defined specifically.
Could the resolution order of the gestures be somehow enhanced to check for more general gesture if no element-specific gesture is identified?
This seems to work ok for the right mouse context menu, even the mouse button shortcut (right-left/ left-right) works ok everywhere on the page (however, in Opera this also works on page tabs, or even tabbar space - but this is probably worked on in this issue anyway.)
thanks and regards,
                          vbr

**Comment by Emdek** [comment] 2015-10-09 21:12
@vbr, sure, it is the sanest way to solve that, as long as more specific group doesn't override more generic gesture then we should match it.

**Comment by Emdek** [comment] 2015-10-23 18:19
@Chocimier, there seems to be a regression when dragging scrollbar.
I guess that we need some exception, maybe even for all left mouse button clicks (as initial step at least) as it also interferes with selection and drag and drop.

**Comment by VSHY** [comment] 2015-10-30 11:19
Please, add action for scroll(middle)-double-click on tab: there is should open blank page (or Express-panel, if it was set in settings) in current tab. It would be very convenient. I very much don't have this ability.

**Comment by Emdek** [comment] 2015-11-07 22:21
@VSHY, what do you mean by "Express-panel"?
There will be only few predefined gestures, but you can add own using UI (#633) or directly in configuration file of mouse profile.

**Comment by VSHY** [comment] 2015-11-10 12:51
@Emdek 
I apologize for my english)... "Express-panel" is the same as "Spead Dial".

**Comment by VSHY** [comment] 2015-11-11 23:48
Right-click on tab is inaccessible in the build 97.

**Comment by vbr** [comment] 2015-11-12 09:52
Hi, many thanks for the improvements of the mouse gesture handling in the recent build 97. 
However, there seems to be some regression regarding mouswheel click on a link. Instead of opening the linked page in a new tab, tha current tab is closed instead (as if the tab would be clicked with mouswheel/middle mouse button).
I can confirm the inaccessible context menu on the tabs mentioned above.
(Win7, Otter 32bit, build 97)
Regards,
   vbr

**Comment by beastie1** [comment] 2015-11-12 20:23
I can confirm there is no context menu when I right-click a tab (latest build).

Also tabs can't be moved by dragging them.

**Comment by Emdek** [comment] 2015-11-12 21:39
@VSHY, @vbr, @beastie1, all these issues should be fixed now, I'll push updated packages soon.

**Comment by beastie1** [comment] 2015-11-14 15:47
Is it only me or is the context menu not displayed anymore for anything other than links? That is neither in blank space nor in regular text selection.

**Comment by beastie1** [comment] 2015-11-14 17:16
Also the tab's context menu doesn't have the usual clone, pin, etc. commands anymore.

**Comment by beastie1** [comment] 2015-11-14 17:20
I have another issue with **pressMiddle**. Since it has been set to StartMoveScroll, I've been unable to paste text as I previously could. I'd like to change it back to the old behavior but **pressMiddle=Paste** doesn't seem to do anything.

**Comment by Emdek** [comment] 2015-11-14 22:50
@beastie1, tab bar should be fixed now, but I can't reproduce that issue with missing context menu, are you using custom mouse profile?
That third issue should be fixed soon.

**Comment by beastie1** [comment] 2015-11-14 23:07
I tried with a blank profile **otter-browser --profile /tmp/test --cache /tmp/test/cache**

Within any page, the context menu is shown only for links.

(Webkit 5.4.1)

**Comment by cofi89** [comment] 2015-11-16 04:21
> Within any page, the context menu is shown only for links (text links and image links).

Same here, using webkit 5.3.2.

**Comment by pmattern** [comment] 2015-11-16 12:58
... and using QtWebKit 5.5.1 (Arch Linux), too.

**Comment by beastie1** [comment] 2015-11-16 21:13
Great! But for some reason the "password" (**<input type="password">**)editboxes are excluded.

**Closed** 2015-11-16 22:56 UTC
Labels: enhancement, status: in progress

**Comment by VSHY** [comment] 2015-11-16 23:14
The context menu is missing also on selected text, page and some other elements.

**Comment by VSHY** [comment] 2015-11-18 11:31
One can't edit a mouse actions and gestures profiles because buttons are desibled in that dialog.

**Comment by Emdek** [comment] 2015-11-18 18:19
@VSHY, that UI has own ticket and it's known, it's not finished yet. :-P

**Comment by midluk** [comment] 2016-02-12 10:31
Mouse gestures (especially the "close tab" gesture) do not work on special tabs like the "Transfers Manager" (generally all the about:* tabs). Would be great to see that fixed.

**Comment by Emdek** [comment] 2016-02-16 21:17
@midluk, yes, it is known limitation, we will try to do something about that in the future.
