### ISSUE TITLE
Cannot remove any addon

### ISSUE THREAD

**Issue by fturco** [OtterBrowser/otter-browser#1338] opened 2017-04-10 12:31 UTC
After having installed some addons in Otter browser I noticed they don't work at all, so now I'd like to remove them, but I can't.

Steps:
1. Go to about:addons
2. Right click on the addon I want to remove

Result: "Remove addon..." is gray and cannot be selected.

As a workaround I can remove addons manually by closing Otter and removing the `~/.config/otter/scripts` directory.

I tried the Rai/Mediaset/La7 addons by [Andrea Lazzarotto](https://greasyfork.org/en/users/2482-lazza).

I have `www-client/otter-0.9.12` on a Gentoo Linux system.

**Comment by Emdek** [comment] 2017-04-10 20:21
Duplicate of subtask from #1091.

**Closed by Emdek** 2017-04-10 20:21 UTC
Labels: duplicate
