### ISSUE TITLE
Dialog for presenting site information

### ISSUE THREAD

**Issue by Emdek** [OtterBrowser/otter-browser#1000] opened 2015-11-22 07:28 UTC
We need solution similar to that used by Chromium, a dialog that shows information like:
* connection details (including certificate viewer, list of SSL errors, used cipher etc.);
* information about blocked elements;
* shortcut to Website Preferences.

Most of required data is already exposed by ``WebWidget``.
Dialog should be accessible using action that can be also triggered by clicking on badge in address field.
After implementing this one we could stop showing SSL errors dialog for less important errors (like self signed certificates).

**Comment by srgloureiro** [comment] 2015-11-22 10:39
YES!!!
Issue number 1000! Since the beginning there have been 690 days. Almost 1.5 issues per day.

**Comment by Emdek** [comment] 2015-11-22 15:20
Initial version of this dialog (just connection details for now) was added in b96008668e97177da40b2399824c3504b2217721.

**Comment by Emdek** [comment] 2015-11-22 15:39
Also it could be a good idea to add more tabs, in manner similar to that of Firefox (but without following their ugly design for dialog itself).

**Comment by beastie1** [comment] 2015-11-22 17:48
I know it's still in early development but I'd like to share some observations and suggestions.

Clicking the badge icon more than once opens the dialog as many times.

Could you make the dialog togglable so that when you click the badge it shows the dialog and when you click it again it closes it?

Also could it be docked just below the badge icon/address bar (less eye movement)?

**Comment by Emdek** [comment] 2015-11-22 20:41
> Clicking the badge icon more than once opens the dialog as many times.

Indeed, should be easy to fix.

> Could you make the dialog togglable so that when you click the badge it shows the dialog and when you click it again it closes it?

I can consider that later but I won't promise that it will end up that way. ;-)

> Also could it be docked just below the badge icon/address bar (less eye movement)?

I'm planning such mode in future, to be applicable also for permission bars etc.

**Comment by beastie1** [comment] 2015-11-24 19:36
Otter is crashing with a segmentation fault.

To reproduce, click the badge icon, close it with the 'x' icon and click the badge again.

**Comment by beastie1** [comment] 2015-11-24 19:36
Otter is crashing with a segmentation fault.

To reproduce, click the badge icon, close it with the 'x' icon and click the badge again.

**Comment by VSHY** [comment] 2015-11-26 00:34
@Emdek 
Please, check the right-click on the badge icon.

**Comment by JavaScriptGangstaCat** [comment] 2015-11-29 01:57
The Site Information dialog show ECDH exchange key even for websites using ECDHE. One can see this on a website like https://cc.dcsec.uni-hannover.de/

Otter say the key exchange on this website is ECDH but the website says that the connection uses *E*CDHE-RSA-AES256-GCM-SHA384 and not ECDH-RSA-AES256-GCM-SHA384 which is different.

**Comment by Emdek** [comment] 2015-11-29 06:57
@JavaScriptGangstaCat, we are just showing information from QtNetwork, so it appears to be some bug in SSL handling there, maybe Windows specific.
I'm getting this output under Linux:
http://im9.eu/picture/xv2946

**Comment by NimGangstaCat** [comment] 2015-11-29 14:46
@Emdek I get the same output under Windows but the websites says:
```
This connection uses TLSv1.2 with **E**CDHE-RSA-AES256-GCM-SHA384 and a 256 Bit key for encryption.
```

On the website, both ECDHE and ECDH suites are listed to be accepted by Otter. So there is a bug here from the key exchange method reporting if the website says we use ECDHE but Otter say we use ECDH. Maybe an upstream bug?

**Comment by JavaScriptGangstaCat** [comment] 2015-11-29 14:48
@Emdek I get the same output under Windows but the websites says:

> This connection uses TLSv1.2 with ECDH**E**-RSA-AES256-GCM-SHA384 and a 256 Bit key for encryption.

On the website, both ECDHE and ECDH suites are listed to be accepted by Otter. So there is a bug here from the key exchange method reporting if the website says we use ECDHE but Otter say we use ECDH. Maybe an upstream bug?

**Comment by VSHY** [comment] 2015-11-30 12:19
@Emdek
Please, check Encoding field, it is always equals 'unknown'.

**Comment by Emdek** [comment] 2015-11-30 12:32
@JavaScriptGangstaCat, possible, we are using ``QSslCipher::keyExchangeMethod()`` to get this name.
I've checked in Qt sources but couldn't find where it is set...

@VSHY, yes and for now it will stay this way, as there is no API to get this value in sane way (even when forcing value using Encoding menu).

**Closed** 2015-11-30 18:37 UTC
Labels: component: GUI, enhancement, severity: high priority, status: in progress

**Comment by beastie1** [comment] 2015-11-30 20:57
Could the dialog be made a little larger?

![screenshot-otter_30112015-225431](https://cloud.githubusercontent.com/assets/6757832/11484237/9dc018fa-97b5-11e5-8a49-33888cda472a.jpg)

**Comment by Emdek** [comment] 2015-11-30 21:01
@beastie1, it's generic issue caused by too small parent widget (#810), most likely I'll try to fix it after beta as it's easy to break stuff while changing that...
I could try to improve it a bit but it won't go away without bigger changes.

**Comment by VSHY** [comment] 2015-12-02 14:09
Website Information dialog is still displayed by right-click on the badge icon.

**Comment by Emdek** [comment] 2015-12-02 16:59
@VSHY, uhm, odd, I can reproduce that only under Windows.

**Comment by VSHY** [comment] 2015-12-02 17:41
@Emdek 
Yes, I always test under Win7.

P.S. The same behaviour is on the icon in the search field.

**Comment by Emdek** [comment] 2015-12-02 18:45
@VSHY, indeed, fixed.
