### ISSUE TITLE
[QtWebEngine] Mouse Scroll Button fails to open links on new tabs

### ISSUE THREAD

**Issue by ghost** [OtterBrowser/otter-browser#1036] opened 2016-01-02 04:05 UTC
Mouse Scroll Button appears to fail opening links on new tabs, but they do open, just can't see them.

Using youtube as an example, use Mouse Scroll Button on a video (open link on a new tab) no tab will open, but it's possible to hear the audio from that video

Otter 0.9.09 Beta 9 QtWebEngine
Windows 7 x64

**Comment by ZarkBit** [comment] 2016-01-27 23:46
Fixed with Weekly 108 QtWebEngine

**Comment by ZarkBit** [comment] 2016-02-03 21:41
Still  occurs with Weekly 109

**Comment by Emdek** [comment] 2016-03-25 22:50
@ZarkBit, basically they open but show blank until reload?
It works that way for me and is suspicious, like failing to render when widget is under another widget.

**Comment by Emdek** [comment] 2017-01-31 07:32
I cannot reproduce it with current master (Linux and Windows).

**Closed by Emdek** 2017-01-31 07:32 UTC
Labels: not reproducible anymore
