### ISSUE TITLE
Wrong tab switcher behavior

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#1257] opened 2017-01-30 19:31 UTC
The **Ctrl+Tab** combination toggles between the current and the "next" tab as soon as it is pressed, before the tab switcher is even displayed.

It should switch only to the selected tab, and only when the **Ctrl** key is released.

**Comment by Frenzie** [comment] 2017-01-30 19:51
Yup, it messes up the tab order.

**Comment by Emdek** [comment] 2017-02-03 17:34
Sounds like duplicate of #1016 .

**Closed by Emdek** 2017-02-03 17:34 UTC
Labels: duplicate

**Comment by beastie1** [comment] 2017-02-03 20:21
I opened this ticket to report a *recent regression* while that other ticket is more than a year old. I didn't notice this behavior before very recently after some commits. Are you sure it was like that all that time?

**Comment by Emdek** [comment] 2017-02-03 20:40
@beastie1, I doubt that it changed recently, the only thing changed in tab switcher in months (except license header cleanup and changing `NULL` to `nullptr`) was marking unloaded tabs using special color.

**Comment by beastie1** [comment] 2017-02-04 19:24
Ah, my bad!
