### ISSUE TITLE
AppImage on Linux 64bit crashes

### ISSUE THREAD

**Issue by sotel** [OtterBrowser/otter-browser#1406] opened 2017-09-03 01:03 UTC
New AppImage **otter-browser-0.9.91-weekly191-x86_64.AppImage** cannot find libssl and doesn't start:
```
Loading /usr/lib64/libssl.so.1.0.0
Loading /usr/lib64/libssl.so.1.0.1
Loading /usr/lib64/libssl.so.1.0.2
Loading /usr/lib64/libssl.so.1.0
Loading /usr/lib64/libssl.so.1
Loading /usr/lib64/libssl.so.10
Loading /usr/lib64/libssl.so
Loading /lib64/libssl.so.1.0.0
Loading /lib64/libssl.so.1.0.1
Loading /lib64/libssl.so.1.0.2
Loading /lib64/libssl.so.1.0
Loading /lib64/libssl.so.1
Loading /lib64/libssl.so.10
Loading /lib64/libssl.so
Loading /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
Loading /usr/lib/x86_64-linux-gnu/libssl.so.1.0.1
Loading /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
./otter-browser: /tmp/user/1000/tmp.DyV8h7RPqR/libssl.so.10: version `libssl.so.10' not found (required by ./lib/libQt5Network.so.5)
./otter-browser: /tmp/user/1000/tmp.DyV8h7RPqR/libcrypto.so.10: version `OPENSSL_1.0.1' not found (required by ./lib/libQt5Network.so.5)
./otter-browser: /tmp/user/1000/tmp.DyV8h7RPqR/libcrypto.so.10: version `OPENSSL_1.0.1_EC' not found (required by ./lib/libQt5Network.so.5)
./otter-browser: /tmp/user/1000/tmp.DyV8h7RPqR/libcrypto.so.10: version `libcrypto.so.10' not found (required by ./lib/libQt5Network.so.5)

```
This libs installed on my machine shouldn't be necessary to run Otter (because we speak about an AppImage) but only for you to know:
_ls -Al /usr/lib/x86_64-linux-gnu/libssl*_ shows:
```
-rw-r--r-- 1 root root 349K Jun  1 06:57 /usr/lib/x86_64-linux-gnu/libssl3.so
-rw-r--r-- 1 root root 698K Jun  4 19:15 /usr/lib/x86_64-linux-gnu/libssl.a
lrwxrwxrwx 1 root root   15 Jun  4 19:15 /usr/lib/x86_64-linux-gnu/libssl.so -> libssl.so.1.0.2
-rw-r--r-- 1 root root 422K Jun  4 19:15 /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
-rw-r--r-- 1 root root 433K Jun  5 11:40 /usr/lib/x86_64-linux-gnu/libssl.so.1.1

```
and 
_ls -Al /usr/lib/x86_64-linux-gnu/libcrypto*_ shows:
```
-rw-r--r-- 1 root root 4.6M Jun  4 19:15 /usr/lib/x86_64-linux-gnu/libcrypto.a
lrwxrwxrwx 1 root root   18 Jun  4 19:15 /usr/lib/x86_64-linux-gnu/libcrypto.so -> libcrypto.so.1.0.2
-rw-r--r-- 1 root root 2.4M Jun  4 19:15 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2
-rw-r--r-- 1 root root 2.6M Jun  5 11:40 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
```

Infos about this machine:
_uname -a_:
```
Linux pythagoras 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux
```

Cheers!
Joerg

**Comment by Emdek** [comment] 2017-09-03 06:55
@sotel, latest AppImage was attempting to solve previous issues, but it failed, OpenSSL has too unstable ABI...
There is one more approach left to try.

Duplicate of #1233.

**Closed by Emdek** 2017-09-03 06:55 UTC
Labels: duplicate
