### ISSUE TITLE
Building fails on all OS' if optional libhunspell-dev is missing

### ISSUE THREAD

**Issue by JulianGro** [OtterBrowser/otter-browser#1684] opened 2021-07-11 04:10 UTC
This happens on Ubuntu 20.04, Ubuntu 18.04, Windows, and MacOS.
Here is the output on Windows: https://gist.github.com/JulianGro/ebb53c585bbc77c22a7474063127e4ac

**Comment by Frenzie** [comment] 2021-07-11 07:41
Mnior edit to the title because my response when seeing that was "…and?" ;-)

**Comment by Emdek** [comment] 2021-07-13 12:44
Seems to be a duplicate of #1683.

**Closed by Emdek** 2021-07-13 12:44 UTC
