### ISSUE TITLE
disapearing tab label while dragging

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#968] opened 2015-10-22 20:18 UTC
Hi,
I just noticed a minor glitch - the title text of the tabs disapears temporarily, when the tabs are rearranged by dragging. After releasing the mouse button the text is restored again.
(Win7, Otter 32bit, weekly 94).
regards,
   vbr

**Comment by beastie1** [comment] 2015-10-22 20:49
Duplicate of #859?

**Closed** 2015-10-22 20:52 UTC
Labels: duplicate
