### ISSUE TITLE
Remember form textarea input

### ISSUE THREAD

**Issue by gjedeer** [OtterBrowser/otter-browser#1232] opened 2017-01-04 10:21 UTC
Minor problem: ctrl-left arrow goes back in history instead of placing cursor at the previous word in textarea

Actual problem: pressing forward or ctrl-right retains one-line text input boxes, but not textarea.

The problem is happening on Github New Issue page. Easy to reproduce, write something in the "leave a comment" box, go back, go forward. It's way too easy to go back by accident.

**Comment by gjedeer** [comment] 2017-01-04 10:21
beta12, from appimage, xubuntu 16.04

**Comment by Emdek** [comment] 2017-01-28 15:07
Duplicate of #151.

**Closed by Emdek** 2017-01-28 15:07 UTC
Labels: duplicate
