### ISSUE TITLE
AutoHide option for bars and sidebars

### ISSUE THREAD

**Issue by DI555** [OtterBrowser/otter-browser#1034] opened 2015-12-26 13:50 UTC
it would be very useful for bars and sidebars to have a visibility option - AutoHide !!!
The way when moving a cursor to the place where bar or sidebar must be - bar or sidebar will be appeared!
and if not - will be hidden...

I hope it'll be great especially for full screen mode using!!!

**Comment by lollox** [comment] 2015-12-27 17:19
I think it's a duplicate of this: https://github.com/OtterBrowser/otter-browser/issues/764#issuecomment-88393397 :)

**Closed** 2015-12-27 22:10 UTC
Labels: duplicate
