### ISSUE TITLE
Import bookmarks not working

### ISSUE THREAD

**Issue by Vistaus** [OtterBrowser/otter-browser#1701] opened 2022-01-22 13:12 UTC
Importing bookmarks seems to be broken. I tried to import the HTML bookmarks file created by Falkon, but after starting the import process, Otter says “Failed to export data”. Which is weird, since I'm trying to import, not export. But regardless, it doesn't import anything.

Using latest git master.

**Comment by Emdek** [comment] 2022-01-22 21:23
@Vistaus, are you using QtWebEngine backend?
The message is wrong, but result was caused by lack of import capability in that backend.
It will require cleaning up and merging of  #1614.

**Comment by Vistaus** [comment] 2022-01-23 10:47
Yes, QtWebEngine. Is there a workaround? 'Cause I need my bookmarks and I have too many to manually recreate them in Otter.

**Comment by Emdek** [comment] 2022-01-23 18:00
@Vistaus, the easiest way seems to be to use QtWebKit backend for import.

**Comment by Vistaus** [comment] 2022-01-24 16:36
> @Vistaus, the easiest way seems to be to use QtWebKit backend for import.

Yes, that worked! Thank you! 🙂

**Comment by Vistaus** [comment] 2022-01-24 16:38
Btw, it shouldn't be hard to implement this on QtWebEngine builds. Falkon and Viper, both QtWebEngine web browsers, have implemented this.

**Comment by Emdek** [comment] 2022-01-24 16:59
@Vistaus, see that PR, it needs cleanup and then it can be merged, bringing that feature to QtWebEngine.

**Closed** 2022-01-24 17:00 UTC
Labels: bug, component: GUI
