### ISSUE TITLE
Segfault when removing Tabbar and then Menubar

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#1386] opened 2017-07-18 10:23 UTC
Steps to reproduce:

1. Run `otter-browser --profile /tmp/null` (i.e. fresh profile)
2. Choose View / Tabbar to remove Tabbar
3. View / Menubar to remove Menubar

**Comment by ersi-dnd** [comment] 2017-07-18 10:32
The reason is probably that the big Menubutton is hardcoded to appear on Tabbar when Menubar is removed. When Opera introduced that big button, it was totally wrong.

**Comment by m4sk1n** [comment] 2017-07-20 11:50
@ersi-dnd, I can't reproduce it, tried several times, what version of Otter Browser do you use?

**Comment by ersi-dnd** [comment] 2017-07-20 15:00
@m4sk1n I guess you are right. I pulled the latest Git version and the problem is gone.

Let's change this thread to something else: Help > About and `otter-browser -v` are useless when trying to determine the browser version. Both before and after the upgrade both places show the same thing.

**Comment by m4sk1n** [comment] 2017-07-21 09:25
@ersi-dnd, if you are using weeklies or releases, it's showing proper version. When using git master, it's normal that you won't get any useful info from here…

**Comment by m4sk1n** [comment] 2017-07-21 09:25
If your problem is solved, can you close the issue, please?

**Closed** 2017-07-24 19:52 UTC
Labels: invalid
