### ISSUE TITLE
Shift-Arrow link navigation

### ISSUE THREAD

**Issue by gjedeer** [OtterBrowser/otter-browser#1231] opened 2017-01-04 10:16 UTC
I could not find a setting or an entry in Keyboard Shortcuts to make Shift+arrow keys navigate between links, like classic Opera did. Is it possible to add this feature?

**Comment by mariokamenjak** [comment] 2017-01-05 22:08
I would love to have it one day as well.

**Comment by ersi-dnd** [comment] 2017-01-26 15:04
Tab does something like this, but yes, could be better. New Opera and Vivaldi have created a flashy version of links navigation.

**Comment by Emdek** [comment] 2017-01-28 18:42
Duplicate of #119.

**Closed by Emdek** 2017-01-28 18:42 UTC
Labels: duplicate
