### ISSUE TITLE
Home button doesn't work for 0.9.12-0.3.beta12gitd82cbcc.fc24

### ISSUE THREAD

**Issue by lukasz-r** [OtterBrowser/otter-browser#1355] opened 2017-04-21 10:14 UTC
I've just updated otter under Fedora 24 KDE to a new version (details given below) and the home navigation button stopped working. I've checked the settings, deleted the button, added it again, no result.

The CTRL+SPACE shortcut still works.
This is my current otter version:

Otter 0.9.91-dev
0.9.12-0.3.beta12gitd82cbcc.fc24
Web backend: WebKit Backend (legacy) 538.1.
SSL library version: OpenSSL 1.0.2k-fips 26 Jan 2017.
This program uses Qt version 5.6.2.

**Comment by Frenzie** [comment] 2017-04-21 10:30
Duplicate of #1342?

**Comment by Emdek** [comment] 2017-04-21 10:32
@Frenzie, probably not, seems to be different regression caused by actions rewrite, I'll take a closer look later.

BTW, it seems that they package random commits or weeklies (even then it is more like a random commit since they don't have tags)...

**Closed** 2017-04-21 18:08 UTC
Labels: bug, component: core

**Comment by lukasz-r** [comment] 2017-04-21 18:15
@Emdek Thanks a lot for a quick resolution!

**Comment by Emdek** [comment] 2017-04-21 18:39
@lukasz-r, no problem, just doing my job. ;-)
