### ISSUE TITLE
Exposing MDI controls

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#999] opened 2015-11-21 21:53 UTC
Would it be possible to have MDI controls (minimize, maximize and close) on the rightmost side of the menu bar just like in Opera?

Currently there is the minimize and maximize tab actions, but they're only available as text, not the usual "minus" and "square" icons. Plus they don't work very well it seems.

As for the close tab icon, I think it would be better to have the generic "x" icon.

**Comment by VSHY** [comment] 2015-11-23 15:05
Related ticket: #915.

**Comment by Emdek** [comment] 2015-11-23 21:19
@beastie1, this will be doable by customizing existing actions after implementing #756.
Due to limitations of ``QMdiArea`` and ``QMenuBar`` this will be the only feasible option that doesn't require adding custom widget.

Duplicate of #70.

**Closed by Emdek** 2015-11-23 21:19 UTC
Labels: duplicate
