### ISSUE TITLE
QtWebEngine based build for Windows?

### ISSUE THREAD

**Issue by 3oheicrw** [OtterBrowser/otter-browser#1735] opened 2022-07-03 21:55 UTC
Otter 1.0.03 released for a while but we still can't get a QtWebEngine based build for Windows? The only thing I found is a WebKit based build for Windows XP.

**Comment by Emdek** [comment] 2022-07-04 20:40
Right the build setup for Windows is still broken.

Duplicate of #1702.

**Closed by Emdek** 2022-07-04 20:40 UTC
Labels: duplicate
