### ISSUE TITLE
Keyboard accelerators missing from the menu bar

### ISSUE THREAD

**Issue by Zero3K** [OtterBrowser/otter-browser#1098] opened 2016-03-29 03:21 UTC
The menu bar is missing keyboard accelerators which is causing the Alt + F, etc. key to not select it or one of its menus.

**Comment by beastie1** [comment] 2016-03-29 18:33
Otter doesn't provide that feature yet. Related to/duplicate of #510

**Closed** 2016-03-30 05:41 UTC
Labels: duplicate
