### ISSUE TITLE
Flesh out default keyboard shortcuts/mouse gestures

### ISSUE THREAD

**Issue by Zero3K** [OtterBrowser/otter-browser#1083] opened 2016-03-27 02:44 UTC
I think that more shortcuts from Firefox, etc. should be added to them.

**Comment by Zero3K** [comment] 2016-03-28 00:48
The guy who got me to write this request (pereba) wants alt+enter to open the url that's inputted into the address bar in a new tab.

**Comment by Emdek** [comment] 2016-06-15 12:31
Duplicate of #789 .

**Closed by Emdek** 2016-06-15 12:31 UTC
Labels: duplicate
