### ISSUE TITLE
Feature: Add ipfs protocol support

### ISSUE THREAD

**Issue by uzerus** [OtterBrowser/otter-browser#1344] opened 2017-04-13 23:36 UTC
https://ipfs.io/
development currently in alpha, but anyway its WORKING alpha. its more fast than http.

here you have an experimental project https://github.com/beakerbrowser/beaker

**Comment by beastie1** [comment] 2017-04-14 08:52
Duplicate of #1237

**Comment by Frenzie** [comment] 2017-04-14 08:56
Also closing this one then. Could be nice in the future! :-)

**Closed by Frenzie** 2017-04-14 08:56 UTC
